#!/usr/bin/env bash
# publish_github_release.sh — collect a GitForge lane release run's
# dist/ from the lane host, verify its checksums, and publish the
# GitHub release from those artifacts.
#
# Run on the workstation (gh must be authenticated). The lane never
# sees GitHub credentials: it builds dist/ and writes it into the job
# workspace on the lane host; this script resolves the workspace from
# the lane's audit.db (read-only), copies it over, and republishes.
# GitHub is the tracking/sharing mirror — the build path of record is
# the GitForge aegis-release pipeline.
#
# Usage: publish_github_release.sh <pipeline_run_id> <summary_file>
#   <pipeline_run_id>  GitForge pipeline run whose release-build job
#                      produced dist/
#   <summary_file>     one-paragraph release summary; the release body
#                      becomes: tag line, summary, CHANGELOG section
# Environment:
#   GITFORGE_HOST   lane host (default mkinney@192.168.1.202)
#   GITFORGE_DB     lane audit.db (default matches the deployment)
#   GITHUB_REPO     target repo (default aliasfoxkde/aegis)

set -euo pipefail

GITFORGE_HOST="${GITFORGE_HOST:-mkinney@192.168.1.202}"
GITFORGE_DB="${GITFORGE_DB:-/home/mkinney/work/gitforge-audit-20260822/audit.db}"
GITHUB_REPO="${GITHUB_REPO:-aliasfoxkde/aegis}"

if [ "$#" -ne 2 ]; then
  echo "usage: publish_github_release.sh <pipeline_run_id> <summary_file>" >&2
  exit 2
fi
run_id="$1"
summary_file="$2"
if [ ! -f "$summary_file" ]; then
  echo "summary file not found: $summary_file" >&2
  exit 2
fi
if ! printf '%s' "$run_id" | grep -Eq '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'; then
  echo "REFUSING: pipeline_run_id is not a uuid" >&2
  exit 2
fi

version="$(sed -n 's/^version = "\(.*\)"$/\1/p' Cargo.toml | head -1)"
if [ -z "$version" ]; then
  echo "cannot read workspace version from Cargo.toml (run from the repo root)" >&2
  exit 1
fi
tag="v$version"

# Resolve the release-build job's workspace directory from the lane
# database. run_id crosses as argv, never interpolated into the SQL.
workspace="$(ssh "$GITFORGE_HOST" "python3 - '$run_id' '$GITFORGE_DB' <<'PY'
import sqlite3
import sys

connection = sqlite3.connect('file:' + sys.argv[2] + '?mode=ro', uri=True)
row = connection.execute(
    'SELECT working_dir FROM jobs'
    ' WHERE pipeline_run_id = ? AND name = ?'
    ' ORDER BY created_at LIMIT 1',
    (sys.argv[1], 'release-build'),
).fetchone()
print(row[0] if row and row[0] else '')
PY
")"
if [ -z "$workspace" ]; then
  echo "no release-build job workspace found for run $run_id" >&2
  exit 1
fi
echo "lane workspace: $workspace"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
scp -q -r "$GITFORGE_HOST:$workspace/dist" "$work/dist"

echo "--- verifying checksums"
( cd "$work/dist" && sha256sum -c checksums.txt )

expected=(
  aegis-darwin-arm64.tar.gz
  aegis-darwin-x86_64.tar.gz
  aegis-linux-arm64.tar.gz
  aegis-linux-x86_64.tar.gz
  aegis-windows-x86_64.tar.gz
  aegis-wasm.wasm
  checksums.txt
  release-attestation.json
  source.tar.gz
  source.zip
)
for asset in "${expected[@]}"; do
  if [ ! -f "$work/dist/$asset" ]; then
    echo "missing release asset: $asset" >&2
    exit 1
  fi
done

echo "--- composing release notes"
changelog="$(awk -v start="## [$version]" \
  'index($0, start) == 1 { seen = 1; next } seen && /^## \[/ { exit } seen' \
  CHANGELOG.md)"
{
  printf '%s\n\n' "$tag"
  cat "$summary_file"
  printf '\n%s\n' "$changelog"
} > "$work/notes.md"

echo "--- creating GitHub release $tag on $GITHUB_REPO"
gh release create "$tag" \
  --repo "$GITHUB_REPO" \
  --verify-tag \
  --title "$tag" \
  --notes-file "$work/notes.md" \
  "$work/dist"/*

published="$(gh api "repos/$GITHUB_REPO/releases/tags/$tag" \
  --jq '[.assets[].name] | sort | join("\n")')"
for asset in "${expected[@]}"; do
  if ! grep -Fqx -- "$asset" <<<"$published"; then
    echo "asset missing after publish: $asset" >&2
    exit 1
  fi
done

echo "published $tag with ${#expected[@]} template assets (+ Source code zip/tar.gz generated by GitHub)"
