//! Accessibility patterns - WCAG compliance, screen reader support

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "missing-alt-text".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r"<img[^>]*>".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Image missing alt text".to_string(),
            reference: Some("https://www.w3.org/WAI/tutorials/images/alt-text/".to_string()),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "image".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-aria-label".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r"<button[^>]*>".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Interactive element missing ARIA label".to_string(),
            reference: Some("https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/".to_string()),
            tags: vec!["accessibility".to_string(), "aria".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-lang-attribute".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r"<(?:!DOCTYPE|html)[^>]*>".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "HTML document missing language attribute".to_string(),
            reference: Some("https://www.w3.org/WAI/tutorials/page-structure/".to_string()),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "language".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "empty-link-text".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r"<a[^>]*>\s*</a>".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Link with empty or missing text".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "links".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-form-label".to_string(),
            category: "accessibility".to_string(),
            match_pattern:
                r"<input[^>]*>"
                    .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Form input missing associated label".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "forms".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-title".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r#"<head>.*</head>"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "HTML document missing title element".to_string(),
            reference: Some("https://www.w3.org/WAI/WCAG21/Understanding/page-titled".to_string()),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "title".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-meta-viewport".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r#"<head>.*</head>"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "HTML document missing viewport meta tag".to_string(),
            reference: Some(
                "https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "mobile".to_string(),
                "viewport".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "low-color-contrast".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r"color:\s*(#[0-9a-fA-F]{3,3}|rgba?\()".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Low color contrast may affect accessibility".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "color".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-skip-link".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r#"<body>.*</body>"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Missing skip navigation link".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "navigation".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-main-landmark".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r#"<body>.*</body>"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Page missing main landmark".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "landmarks".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-heading-level".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r"<h([6-9]|[1-9][0-9])".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Heading level skipped (h6 to hN)".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/heading-levels".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "headings".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "autocomplete-missing".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r#"<input[^>]*>"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Form input may benefit from autocomplete attribute".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "forms".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-focus-indicator".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r#":focus\s*\{[^}]*(?:outline:\s*none|outline:\s*0)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "CSS may be removing focus indicator".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/focus-visible".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "keyboard".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-table-headers".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r#"<table.*</table>"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Data table missing header cells".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "tables".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "video-missing-captions".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r"<video[^>]*>".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Video element missing captions track".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/captions-prerecorded".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "video".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "audio-missing-transcript".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r"<audio[^>]*>".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Audio element missing transcript".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/audio-only-prerecorded".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "audio".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "iframe-missing-title".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r"<iframe[^>]*>".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "iframe missing title attribute".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/iframe-non-empty-accessible-name"
                    .to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "iframe".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "marquee-element".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r"<marquee".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Deprecated marquee element used".to_string(),
            reference: Some(
                "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee".to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "deprecated".to_string(),
                "flashing".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "blinking-content".to_string(),
            category: "accessibility".to_string(),
            match_pattern:
                r"(?i:animation.*:blink|@keyframes\s+.*\s+0%\s*\{\s*[^}]*opacity\s*:\s*0)"
                    .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Blinking content may cause accessibility issues".to_string(),
            reference: Some(
                "https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold"
                    .to_string(),
            ),
            tags: vec![
                "accessibility".to_string(),
                "wcag".to_string(),
                "flashing".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "role-definition".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r#"role="[a-z-]+""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "ARIA role attribute detected".to_string(),
            reference: Some("https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/".to_string()),
            tags: vec![
                "accessibility".to_string(),
                "aria".to_string(),
                "role".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "live-region".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r#"aria-live="(?:polite|assertive)""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "ARIA live region detected".to_string(),
            reference: Some("https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/".to_string()),
            tags: vec![
                "accessibility".to_string(),
                "aria".to_string(),
                "live-region".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "tab-index-usage".to_string(),
            category: "accessibility".to_string(),
            match_pattern: r#"tabindex="[^"]*""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Custom tabindex detected".to_string(),
            reference: Some("https://www.w3.org/WAI/WCAG21/Understanding/focus-order".to_string()),
            tags: vec![
                "accessibility".to_string(),
                "keyboard".to_string(),
                "focus".to_string(),
            ],
            env_var: false,
            binary: false,
        },
    ]
}
