//! AI safety patterns - AI system security, model safety, responsible AI

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "prompt-injection".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(ignore\s+(previous|above|all)|disregard\s+(previous|your)|you\s+are\s+now|forget\s+everything)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential prompt injection detected".to_string(),
            reference: Some("https://www.promptguard.com/".to_string()),
            tags: vec!["ai-safety".to_string(), "prompt-injection".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "system-prompt-leak".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)system\s*prompt|instruction\s*manual|foundation\s*prompt"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Potential system prompt reference detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "prompt".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "unsafe-model-output".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(unsafe|harmful|inappropriate)\s+(output|response|content)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Unsafe model output detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "output".to_string(), "content".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hallucination-risk".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(hallucin|confabula|fabricat).*\b(fact|information|data)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential hallucination risk detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "hallucination".to_string(), "accuracy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "bias-in-training".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(training\s+data|bias|discriminat).*\b(contain|include|inject)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential bias in training data reference".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "bias".to_string(), "training".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "reward-hacking-risk".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(reward\s+hack|optimize\s+wrong|goal\s+mis-spec)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential reward hacking risk detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "alignment".to_string(), "reward".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "mesa-optimization".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(mesa.?optim|inner.?optim|acquisit|power.?seek)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Potential mesa-optimization risk detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "mesa-optimization".to_string(), "alignment".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "model-card-missing".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)model\s*card|model\s*sheet|model\s*document"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Model card or documentation reference".to_string(),
            reference: Some("https://modelcards.withgoogle.com/".to_string()),
            tags: vec!["ai-safety".to_string(), "transparency".to_string(), "documentation".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "ai-bias-report".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(ai\s+bias|fairness\s+report|impact\s+assessment)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "AI bias or fairness assessment reference".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "bias".to_string(), "fairness".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "model-version-tracking".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(model\s+version|model\s+hash|snapshot)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Model version tracking reference".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "versioning".to_string(), "reproducibility".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "evaluation-benchmark".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(MMLU|BIG-Bench|GLUE|HELM|TruthfulQA)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "AI evaluation benchmark reference".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "evaluation".to_string(), "benchmark".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "adversarial-testing".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(adversarial|red\s+team|attack\s+testing)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Adversarial testing reference detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "adversarial".to_string(), "testing".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "interpretability-tool".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(SHAP|LIME|feature\s+importance|attribution)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Interpretability tool reference detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "interpretability".to_string(), "explainability".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "attention-visualization".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(attention\s+map|activation\s+map|gradient\s+viz)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Model visualization reference detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "visualization".to_string(), "interpretability".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "training-data-audit".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(training\s+data\s+audit|data\s+lineage|data\s+provenance)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Training data audit reference detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "data-governance".to_string(), "training".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "consent-for-training".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(consent|opt.?in|permission)\s.*\b(train|use\s+data)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Consent for data training reference detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "consent".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "data-augmentation".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(augment|synthesiz|generate\s+data)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Data augmentation technique reference".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "robustness".to_string(), "training".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "noise-injection".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(noise|inject|fuzz)\s.*\b(input|data|training)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Noise injection technique reference".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "robustness".to_string(), "fuzzing".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "human-in-the-loop".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(human.?in.?the.?loop|HITL|human\s+oversight)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Human-in-the-loop reference detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "human-oversight".to_string(), "control".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "human-approval-required".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(require.*human|human.*approval|human.*sign.?off)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Human approval requirement detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "human-approval".to_string(), "control".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rlhf-reference".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(RLHF|reinforcement\s+learning\s+from\s+human\s+feedback)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "RLHF technique reference detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "rlhf".to_string(), "alignment".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rlhf-reward-model".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(reward\s+model|train\s+reward|preference\s+model)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Reward model training reference detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "reward-model".to_string(), "alignment".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "constitutional-ai".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(constitutional\s+ai|CAI|principle.?based)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Constitutional AI reference detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "constitutional-ai".to_string(), "alignment".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "ai-incident-response".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(ai\s+incident|model\s+fail|incident\s+report)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "AI incident response reference detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "incident-response".to_string(), "safety".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "model-rollback".to_string(),
            category: "ai-safety".to_string(),
            match_pattern: r#"(?i)(rollback|revert|previous\s+version)\s.*\b(model|ai)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Model rollback capability detected".to_string(),
            reference: None,
            tags: vec!["ai-safety".to_string(), "rollback".to_string(), "operations".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
