//! API integration patterns

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "api_versioning".to_string(),
            category: "api_integration".to_string(),
            match_pattern: r#"api.*version.*header|Accept.*application/vnd\.|\/v[0-9]+\/|versioning.*strategy"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Detected potential API key or token: 'api versioning'. Exposing API keys in source code risks unauthorized API access.".to_string(),
            reference: None,
            tags: vec!["api_integration".to_string(), "api_versioning".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "insecure_api_authentication".to_string(),
            category: "api_integration".to_string(),
            match_pattern: r#"Authorization.*Bearer.*token|apiKey.*header|auth.*basic.*credentials"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Detected potential API key or token: 'insecure api authentication'. Exposing API keys in source code risks unauthorized API access.".to_string(),
            reference: None,
            tags: vec!["api_integration".to_string(), "insecure_api_authentication".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "error_handling".to_string(),
            category: "api_integration".to_string(),
            match_pattern: r#"try.*fetch.*catch.*console\.log|response\.ok.*throw|fetch.*catch.*null"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Detected potential API key or token: 'error handling'. Exposing API keys in source code risks unauthorized API access.".to_string(),
            reference: None,
            tags: vec!["api_integration".to_string(), "error_handling".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "graphql".to_string(),
            category: "api_integration".to_string(),
            match_pattern: r#"query.*\{.*\{.*\{.*\}|useQuery.*\[\].*staleTime.*0|mutation.*refetchQueries"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Detected potential API key or token: 'graphql'. Exposing API keys in source code risks unauthorized API access.".to_string(),
            reference: None,
            tags: vec!["api_integration".to_string(), "graphql".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "pagination".to_string(),
            category: "api_integration".to_string(),
            match_pattern: r#"limit.*100\+|page.*size.*large|offset.*pagination|cursor.*pagination"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Detected potential API key or token: 'pagination'. Exposing API keys in source code risks unauthorized API access.".to_string(),
            reference: None,
            tags: vec!["api_integration".to_string(), "pagination".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rate_limiting".to_string(),
            category: "api_integration".to_string(),
            match_pattern: r#"setInterval.*fetch.*1000|for.*fetch.*break|while.*fetch.*condition"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Detected potential API key or token: 'rate limiting'. Exposing API keys in source code risks unauthorized API access.".to_string(),
            reference: None,
            tags: vec!["api_integration".to_string(), "rate_limiting".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rest".to_string(),
            category: "api_integration".to_string(),
            match_pattern: r#"fetch.*\.then.*\.then.*\.catch|await\s+fetch.*await\s+fetch"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Detected potential API key or token: 'rest'. Exposing API keys in source code risks unauthorized API access.".to_string(),
            reference: None,
            tags: vec!["api_integration".to_string(), "rest".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "timeout".to_string(),
            category: "api_integration".to_string(),
            match_pattern: r#"timeout.*0|timeout.*30000|fetch.*timeout.*10000|axios.*timeout.*5000"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Detected potential API key or token: 'timeout'. Exposing API keys in source code risks unauthorized API access.".to_string(),
            reference: None,
            tags: vec!["api_integration".to_string(), "timeout".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "versioning".to_string(),
            category: "api_integration".to_string(),
            match_pattern: r#"\/api\/v1|\/api\/v2|header.*version|Accept.*version"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Detected potential API key or token: 'versioning'. Exposing API keys in source code risks unauthorized API access.".to_string(),
            reference: None,
            tags: vec!["api_integration".to_string(), "versioning".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
