//! Cloud native patterns - Kubernetes, Docker, serverless, microservices

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        // Kubernetes patterns (additional beyond infrastructure.rs)
        Pattern {
            name: "cloud-native-kubernetes-secret".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)kind:\s*Secret".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes Secret resource detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/configuration/secret/".to_string()),
            tags: vec!["kubernetes".to_string(), "secret".to_string(), "cloud".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerfile-exposed".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"EXPOSE\s+(22|23|3306|5432|27017|6379|11211)".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Potentially sensitive port exposed in Dockerfile".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#expose".to_string()),
            tags: vec!["docker".to_string(), "security".to_string(), "network".to_string()],
            env_var: false,
            binary: false,
        },
        // Service mesh patterns
        Pattern {
            name: "istio-virtualservice".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)kind:\s*VirtualService".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Istio VirtualService detected".to_string(),
            reference: Some("https://istio.io/latest/docs/reference/config/networking/virtual-service/".to_string()),
            tags: vec!["istio".to_string(), "service-mesh".to_string(), "kubernetes".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "istio-destinationrule".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)kind:\s*DestinationRule".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Istio DestinationRule detected".to_string(),
            reference: Some("https://istio.io/latest/docs/reference/config/networking/destination-rule/".to_string()),
            tags: vec!["istio".to_string(), "service-mesh".to_string(), "kubernetes".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "istio-peer-authentication".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)kind:\s*PeerAuthentication".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Istio PeerAuthentication detected".to_string(),
            reference: Some("https://istio.io/latest/docs/reference/config/security/peer_authentication/".to_string()),
            tags: vec!["istio".to_string(), "mtls".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "linkerd-service-profile".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)kind:\s*ServiceProfile".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Linkerd ServiceProfile detected".to_string(),
            reference: Some("https://linkerd.io/2.14/reference/service-profiles/".to_string()),
            tags: vec!["linkerd".to_string(), "service-mesh".to_string(), "kubernetes".to_string()],
            env_var: false,
            binary: false,
        },
        // Serverless patterns
        Pattern {
            name: "aws-lambda-function".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)AWSTemplateFormatVersion.*Lambda".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "AWS Lambda function reference detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/lambda/latest/dg/welcome.html".to_string()),
            tags: vec!["aws".to_string(), "lambda".to_string(), "serverless".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "aws-sam-template".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r#"Transform:\s*AWS::Serverless"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "AWS SAM template detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html".to_string()),
            tags: vec!["aws".to_string(), "sam".to_string(), "serverless".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "azure-functions".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)Microsoft\.Web/sites|Functions".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Azure Functions detected".to_string(),
            reference: Some("https://docs.microsoft.com/en-us/azure/azure-functions/".to_string()),
            tags: vec!["azure".to_string(), "functions".to_string(), "serverless".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "google-cloud-function".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)Google::Cloud::Functions".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Google Cloud Function detected".to_string(),
            reference: Some("https://cloud.google.com/functions/docs".to_string()),
            tags: vec!["gcp".to_string(), "functions".to_string(), "serverless".to_string()],
            env_var: false,
            binary: false,
        },
        // Container patterns
        Pattern {
            name: "container-liveness-probe".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)livenessProbe".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Container liveness probe configured".to_string(),
            reference: Some("https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/".to_string()),
            tags: vec!["kubernetes".to_string(), "container".to_string(), "health".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "container-readiness-probe".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)readinessProbe".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Container readiness probe configured".to_string(),
            reference: Some("https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/".to_string()),
            tags: vec!["kubernetes".to_string(), "container".to_string(), "health".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "container-resources".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)resources:\s*requests|resources:\s*limits".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Container resource limits configured".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/".to_string()),
            tags: vec!["kubernetes".to_string(), "container".to_string(), "resources".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "container-security-context".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)securityContext".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Container security context configured".to_string(),
            reference: Some("https://kubernetes.io/docs/tasks/configure-pod-container/security-context/".to_string()),
            tags: vec!["kubernetes".to_string(), "security".to_string(), "container".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "pod-security-policy".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)kind:\s*PodSecurityPolicy".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PodSecurityPolicy detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/security/pod-security-policy/".to_string()),
            tags: vec!["kubernetes".to_string(), "security".to_string(), "policy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "container-privileged".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)privileged:\s*true".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Privileged container detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/security/linux-namespaces/#privileged-containers".to_string()),
            tags: vec!["kubernetes".to_string(), "security".to_string(), "container".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "container-capabilities".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)add:\s*\[.*(SYS_ADMIN|NET_ADMIN|ALL)".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dangerous container capability added".to_string(),
            reference: Some("https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities".to_string()),
            tags: vec!["kubernetes".to_string(), "security".to_string(), "capabilities".to_string()],
            env_var: false,
            binary: false,
        },
        // Service discovery
        Pattern {
            name: "cloud-native-kubernetes-service".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)kind:\s*Service".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes Service detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/services-networking/service/".to_string()),
            tags: vec!["kubernetes".to_string(), "service".to_string(), "discovery".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-endpoints".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)kind:\s*Endpoints".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes Endpoints detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/services-networking/service/".to_string()),
            tags: vec!["kubernetes".to_string(), "service".to_string(), "endpoints".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "consul-service".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)service\s*\{.*name.*}".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Consul service definition detected".to_string(),
            reference: Some("https://www.consul.io/docs/services".to_string()),
            tags: vec!["consul".to_string(), "service-discovery".to_string(), "hashicorp".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "etcd-service".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)etcd.*client|etcd.*peer".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "etcd service configuration detected".to_string(),
            reference: Some("https://etcd.io/docs/".to_string()),
            tags: vec!["etcd".to_string(), "service-discovery".to_string(), "kubernetes".to_string()],
            env_var: false,
            binary: false,
        },
        // Microservices patterns
        Pattern {
            name: "api-gateway".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)kind:\s*APIGateway|Kong|Ambassador|nginx.*ingress".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "API Gateway detected".to_string(),
            reference: None,
            tags: vec!["api-gateway".to_string(), "microservices".to_string(), "ingress".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "circuit-breaker".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)circuitBreaker|CircuitBreaker|circuit_breaker".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Circuit breaker pattern detected".to_string(),
            reference: Some("https://martinfowler.com/bliki/CircuitBreaker.html".to_string()),
            tags: vec!["circuit-breaker".to_string(), "resilience".to_string(), "microservices".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "retry-policy".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)retryPolicy|RetryPolicy|retry_policy|maxAttempts".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Retry policy detected".to_string(),
            reference: None,
            tags: vec!["retry".to_string(), "resilience".to_string(), "microservices".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "timeout-configuration".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)timeout:\s*\d+|requestTimeout|readTimeout".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Timeout configuration detected".to_string(),
            reference: None,
            tags: vec!["timeout".to_string(), "resilience".to_string(), "configuration".to_string()],
            env_var: false,
            binary: false,
        },
        // Observability
        Pattern {
            name: "prometheus-metrics".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)prometheus|metrics.*endpoint|/metrics".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Prometheus metrics endpoint detected".to_string(),
            reference: Some("https://prometheus.io/docs/concepts/data_model/".to_string()),
            tags: vec!["prometheus".to_string(), "monitoring".to_string(), "metrics".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "grafana-dashboard".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)grafana|dashboard.*json".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Grafana dashboard detected".to_string(),
            reference: Some("https://grafana.com/docs/grafana/latest/dashboards/".to_string()),
            tags: vec!["grafana".to_string(), "monitoring".to_string(), "dashboard".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "jaeger-tracing".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)jaeger|opentracing|opentelemetry|traceId".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Distributed tracing configuration detected".to_string(),
            reference: Some("https://www.jaegertracing.io/".to_string()),
            tags: vec!["tracing".to_string(), "observability".to_string(), "distributed".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "fluentd-config".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)fluentd|fluent-bit|logzio".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Fluentd logging configuration detected".to_string(),
            reference: Some("https://www.fluentd.org/".to_string()),
            tags: vec!["logging".to_string(), "fluentd".to_string(), "observability".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "elasticsearch-config".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)elasticsearch|elastic.*search|ELK.*stack".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Elasticsearch configuration detected".to_string(),
            reference: Some("https://www.elastic.co/elasticsearch/".to_string()),
            tags: vec!["elasticsearch".to_string(), "logging".to_string(), "observability".to_string()],
            env_var: false,
            binary: false,
        },
        // Cloud provider specific
        Pattern {
            name: "aws-ecs-task".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)AWS::ECS::TaskDefinition|Fargate".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "AWS ECS task definition detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definitions.html".to_string()),
            tags: vec!["aws".to_string(), "ecs".to_string(), "container".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "aws-eks-cluster".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)AWS::EKS::Cluster".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "AWS EKS cluster detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/eks/latest/userguide/clusters.html".to_string()),
            tags: vec!["aws".to_string(), "eks".to_string(), "kubernetes".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "azure-aks-cluster".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)Microsoft\.ContainerService|aks".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Azure AKS cluster detected".to_string(),
            reference: Some("https://docs.microsoft.com/en-us/azure/aks/".to_string()),
            tags: vec!["azure".to_string(), "aks".to_string(), "kubernetes".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gcp-gke-cluster".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)GKE|GoogleContainerEngine|container.googleapis.com".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GCP GKE cluster detected".to_string(),
            reference: Some("https://cloud.google.com/kubernetes-engine".to_string()),
            tags: vec!["gcp".to_string(), "gke".to_string(), "kubernetes".to_string()],
            env_var: false,
            binary: false,
        },
        // Network policies
        Pattern {
            name: "network-policy-ingress".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)policyTypes.*Ingress|ingress.*CIDR".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Network policy ingress rule detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/services-networking/network-policies/".to_string()),
            tags: vec!["kubernetes".to_string(), "network".to_string(), "policy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "network-policy-egress".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)policyTypes.*Egress|egress.*CIDR".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Network policy egress rule detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/services-networking/network-policies/".to_string()),
            tags: vec!["kubernetes".to_string(), "network".to_string(), "policy".to_string()],
            env_var: false,
            binary: false,
        },
        // Helm
        Pattern {
            name: "helm-release".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)HelmRelease|helm.*release".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Helm release detected".to_string(),
            reference: Some("https://helm.sh/docs/".to_string()),
            tags: vec!["helm".to_string(), "kubernetes".to_string(), "deployment".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "helm-repo".to_string(),
            category: "cloud-native".to_string(),
            match_pattern: r"(?i)helm.*repo.*add|helm.*repo.*update".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Helm repository reference detected".to_string(),
            reference: Some("https://helm.sh/docs/helm/helm_repo/".to_string()),
            tags: vec!["helm".to_string(), "kubernetes".to_string(), "repository".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
