//! Code quality patterns

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "console-log".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"console\.(log|debug|info|warn|error)\s*\(".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Console logging statement detected".to_string(),
            reference: Some("https://eslint.org/docs/rules/no-console".to_string()),
            tags: vec!["debug".to_string(), "logging".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "todo-comment".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"(?i)\b(TODO|FIXME|HACK|XXX)\b".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "TODO/FIXME comment detected".to_string(),
            reference: None,
            tags: vec!["comment".to_string(), "technical-debt".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "debugger-statement".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"\bdebugger\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Debugger statement detected".to_string(),
            reference: None,
            tags: vec!["debug".to_string(), "development".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "print-statement".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"\bprint\s*\(|\bSystem\.out\.print|\bprintln\s*\(|\blog\.(info|debug|warn|error)".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Print statement detected".to_string(),
            reference: None,
            tags: vec!["debug".to_string(), "logging".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "long-function".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"(?s).{200,}".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Long function/method detected (>200 chars)".to_string(),
            reference: Some("https://github.com/b battaglie/code-review-gpt".to_string()),
            tags: vec!["complexity".to_string(), "maintainability".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "commented-code".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"^\s*//\s*(function|const|let|var|if|for|while|return|class|import)".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Commented-out code detected".to_string(),
            reference: None,
            tags: vec!["comment".to_string(), "dead-code".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "magic-number".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"[^a-zA-Z][0-9]{4,}".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Magic number detected".to_string(),
            reference: None,
            tags: vec!["readability".to_string(), "maintainability".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "empty-catch-block".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"catch\s*\([^)]*\)\s*\{\s*\}".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Empty catch block detected".to_string(),
            reference: None,
            tags: vec!["error-handling".to_string(), "anti-pattern".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "nested-callbacks".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"\)\s*\)\s*\)\s*\)".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Deeply nested callbacks detected (callback hell)".to_string(),
            reference: None,
            tags: vec!["complexity".to_string(), "readability".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hardcoded-date".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r#"new\s+Date\(\s*['"]\d{4}-\d{2}-\d{2}"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Hardcoded date detected".to_string(),
            reference: None,
            tags: vec!["hardcoded".to_string(), "date".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "unused-variable".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r#"(?:const|let|var)\s+\w+\s*;"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Potential unused variable".to_string(),
            reference: None,
            tags: vec!["unused".to_string(), "variable".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "code-quality-eval-usage".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r#"eval\s*"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Use of eval() detected".to_string(),
            reference: Some("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval".to_string()),
            tags: vec!["security".to_string(), "dangerous".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "with-statement".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r#"with\s*"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Use of with statement detected".to_string(),
            reference: None,
            tags: vec!["javascript".to_string(), "anti-pattern".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "double-negation".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r#"!![a-zA-Z_]"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Double negation (!!) detected".to_string(),
            reference: None,
            tags: vec!["readability".to_string(), "javascript".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "unused-import".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r#"^import\s+[^;]+\s*;$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Unused import detected".to_string(),
            reference: None,
            tags: vec!["import".to_string(), "unused".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
