//! Code quality patterns

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "console-log".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"console\.(log|debug|info|warn|error)\s*\(".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Console logging statement detected".to_string(),
            reference: Some("https://eslint.org/docs/rules/no-console".to_string()),
            tags: vec!["debug".to_string(), "logging".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "todo-comment".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"(?i)\b(TODO|FIXME|HACK|XXX)\b".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "TODO/FIXME comment detected".to_string(),
            reference: None,
            tags: vec!["comment".to_string(), "technical-debt".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "debugger-statement".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"\bdebugger\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Debugger statement detected".to_string(),
            reference: None,
            tags: vec!["debug".to_string(), "development".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "print-statement".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"\bprint\s*\(|\bSystem\.out\.print|\bprintln\s*\(|\blog\.(info|debug|warn|error)".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Print statement detected".to_string(),
            reference: None,
            tags: vec!["debug".to_string(), "logging".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "excess-line-length".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"(?m)^.{200,}$".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Excessively long line detected (>200 characters)".to_string(),
            reference: None,
            tags: vec!["complexity".to_string(), "maintainability".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "commented-code".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"^\s*//\s*(function|const|let|var|if|for|while|return|class|import)".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Commented-out code detected".to_string(),
            reference: None,
            tags: vec!["comment".to_string(), "dead-code".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "magic-number".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"\b\d{4,}\b".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Magic number detected".to_string(),
            reference: None,
            tags: vec!["readability".to_string(), "maintainability".to_string()],
            env_var: false,
            binary: false,
            // A line-regex rule cannot see naming context, so numeric
            // constants that are idiomatic in every codebase are excluded:
            // calendar years and the byte-size / unit-conversion ladder
            // (1024..16777216, and the 1000 kilo/milli step). Arbitrary
            // thresholds such as 86400 or 65535-styled ports stay flagged.
            exclude: Some(concat!(
                r"\A(?:(?:19|20)\d{2}",
                r"|1000|1024|2048|4096|8192|16384|32768|65536|131072",
                r"|262144|524288|1048576|2097152|4194304|8388608|16777216",
                r")\z"
            )
            .to_string()),
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "empty-catch-block".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"catch\s*\([^)]*\)\s*\{\s*\}".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Empty catch block detected".to_string(),
            reference: None,
            tags: vec!["error-handling".to_string(), "anti-pattern".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "nested-callbacks".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"\)\s*\)\s*\)\s*\)".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Deeply nested callbacks detected (callback hell)".to_string(),
            reference: None,
            tags: vec!["complexity".to_string(), "readability".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "hardcoded-date".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r#"new\s+Date\(\s*['"]\d{4}-\d{2}-\d{2}"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Hardcoded date detected".to_string(),
            reference: None,
            tags: vec!["hardcoded".to_string(), "date".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "var-declaration".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"\bvar\s+[A-Za-z_$][\w$]*\s*=".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Use of 'var' instead of 'let'/'const' (ES6+)".to_string(),
            reference: Some("https://eslint.org/docs/latest/rules/no-var".to_string()),
            tags: vec!["javascript".to_string(), "es6".to_string(), "best-practice".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: vec![
                "js".to_string(),
                "mjs".to_string(),
                "cjs".to_string(),
                "jsx".to_string(),
                "ts".to_string(),
                "tsx".to_string(),
                "vue".to_string(),
                "svelte".to_string(),
            ],
        },
        Pattern {
            name: "code-quality-eval-usage".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"\beval\s*\(".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Use of eval() detected".to_string(),
            reference: Some("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval".to_string()),
            tags: vec!["security".to_string(), "dangerous".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: vec![
                "js".to_string(),
                "mjs".to_string(),
                "cjs".to_string(),
                "jsx".to_string(),
                "ts".to_string(),
                "tsx".to_string(),
                "php".to_string(),
                "py".to_string(),
                "rb".to_string(),
                "vue".to_string(),
                "svelte".to_string(),
            ],
        },
        Pattern {
            name: "with-statement".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"\bwith\s*\(".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Use of with statement detected".to_string(),
            reference: Some("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with".to_string()),
            tags: vec!["javascript".to_string(), "anti-pattern".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: vec![
                "js".to_string(),
                "mjs".to_string(),
                "cjs".to_string(),
                "jsx".to_string(),
                "ts".to_string(),
                "tsx".to_string(),
                "vue".to_string(),
                "svelte".to_string(),
            ],
        },
        Pattern {
            name: "double-negation".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r#"!![a-zA-Z_]"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Double negation (!!) detected".to_string(),
            reference: None,
            tags: vec!["readability".to_string(), "javascript".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "loose-equality".to_string(),
            category: "code-quality".to_string(),
            match_pattern: r"[^=!<>]==[^=]".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Loose equality comparison ('=='); prefer strict equality ('===')".to_string(),
            reference: Some("https://eslint.org/docs/latest/rules/eqeqeq".to_string()),
            tags: vec!["javascript".to_string(), "best-practice".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: vec![
                "js".to_string(),
                "mjs".to_string(),
                "cjs".to_string(),
                "jsx".to_string(),
                "ts".to_string(),
                "tsx".to_string(),
                "vue".to_string(),
                "svelte".to_string(),
            ],
        },
    ]
}
