//! Compliance patterns - regulatory frameworks, standards, certifications

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        // GDPR patterns
        Pattern {
            name: "gdpr-reference".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)gdpr|general\s+data\s+protection".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "GDPR reference detected".to_string(),
            reference: Some("https://gdpr.eu/".to_string()),
            tags: vec!["compliance".to_string(), "gdpr".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gdpr-article-17".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)article\s*17|right\s*to\s*erasure".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GDPR Article 17 (Right to Erasure) reference detected".to_string(),
            reference: Some("https://gdpr.eu/article-17-right-to-erasure/".to_string()),
            tags: vec!["compliance".to_string(), "gdpr".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gdpr-article-25".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)article\s*25|data\s*by\s*design|privacy\s*by\s*design".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GDPR Article 25 (Data Protection by Design) reference detected".to_string(),
            reference: Some("https://gdpr.eu/article-25-data-protection-by-design/".to_string()),
            tags: vec!["compliance".to_string(), "gdpr".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gdpr-article-32".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)article\s*32|security\s*of\s*processing".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GDPR Article 32 (Security of Processing) reference detected".to_string(),
            reference: Some("https://gdpr.eu/article-32-security-of-processing/".to_string()),
            tags: vec!["compliance".to_string(), "gdpr".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        // HIPAA patterns
        Pattern {
            name: "hipaa-reference".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)hipaa|health\s+insurance\s+portability".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "HIPAA reference detected".to_string(),
            reference: Some("https://www.hhs.gov/hipaa/".to_string()),
            tags: vec!["compliance".to_string(), "hipaa".to_string(), "healthcare".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hipaa-phi".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)phi|protected\s*health\s*information".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "HIPAA Protected Health Information (PHI) reference detected".to_string(),
            reference: Some("https://www.hhs.gov/hipaa/for-professionals/special-topics/health-information-privacy/".to_string()),
            tags: vec!["compliance".to_string(), "hipaa".to_string(), "phi".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hipaa-safeguards".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)hipaa\s*safeguards|administrative\s*safeguards|physical\s*safeguards|technical\s*safeguards".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "HIPAA safeguards reference detected".to_string(),
            reference: Some("https://www.hhs.gov/hipaa/for-professionals/security/".to_string()),
            tags: vec!["compliance".to_string(), "hipaa".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        // SOC 2 patterns
        Pattern {
            name: "soc2-reference".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)soc\s*2|service\s*organization\s*control".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "SOC 2 reference detected".to_string(),
            reference: Some("https://www.aicpa.org/soc2".to_string()),
            tags: vec!["compliance".to_string(), "soc2".to_string(), "audit".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "soc2-trust-criteria".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)(security|availability|processing\s*integrity|confidentiality|privacy)\s*(criteria|principle)".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "SOC 2 trust service criteria detected".to_string(),
            reference: Some("https://www.aicpa.org/soc2".to_string()),
            tags: vec!["compliance".to_string(), "soc2".to_string(), "trust-services".to_string()],
            env_var: false,
            binary: false,
        },
        // PCI DSS patterns
        Pattern {
            name: "pci-dss".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)pci\s*dss|payment\s*card\s*industry".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PCI DSS reference detected".to_string(),
            reference: Some("https://www.pcisecuritystandards.org/".to_string()),
            tags: vec!["compliance".to_string(), "pci-dss".to_string(), "payment".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "pci-cardholder-data".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)cardholder\s*data|pan|primary\s*account\s*number".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PCI cardholder data reference detected".to_string(),
            reference: Some("https://www.pcisecuritystandards.org/pci_security/".to_string()),
            tags: vec!["compliance".to_string(), "pci-dss".to_string(), "card-data".to_string()],
            env_var: false,
            binary: false,
        },
        // ISO 27001 patterns
        Pattern {
            name: "iso-27001".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)iso\s*27001|iso\s*iec\s*27001".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "ISO 27001 reference detected".to_string(),
            reference: Some("https://www.iso.org/isoiec-27001-information-security.html".to_string()),
            tags: vec!["compliance".to_string(), "iso27001".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "iso-27002".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)iso\s*27002|information\s*security\s*controls".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "ISO 27002 reference detected".to_string(),
            reference: Some("https://www.iso.org/standard/75652.html".to_string()),
            tags: vec!["compliance".to_string(), "iso27002".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        // NIST frameworks
        Pattern {
            name: "nist-framework".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)nist\s*framework|csf|cybersecurity\s*framework".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "NIST Cybersecurity Framework reference detected".to_string(),
            reference: Some("https://www.nist.gov/cyberframework".to_string()),
            tags: vec!["compliance".to_string(), "nist".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "nist-800-53".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)nist\s*800[-_]?53|sp\s*800[-_]?53".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "NIST SP 800-53 reference detected".to_string(),
            reference: Some("https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final".to_string()),
            tags: vec!["compliance".to_string(), "nist".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "nist-800-190".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)nist\s*800[-_]?190|container\s*security\s*guide".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "NIST SP 800-190 (Container Security) reference detected".to_string(),
            reference: Some("https://csrc.nist.gov/publications/detail/sp/800-190/final".to_string()),
            tags: vec!["compliance".to_string(), "nist".to_string(), "container".to_string()],
            env_var: false,
            binary: false,
        },
        // SOX patterns
        Pattern {
            name: "sox-compliance".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)sox|sarbanes[-_]?oxley".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "SOX compliance reference detected".to_string(),
            reference: Some("https://www.soxlaw.com/".to_string()),
            tags: vec!["compliance".to_string(), "sox".to_string(), "finance".to_string()],
            env_var: false,
            binary: false,
        },
        // FedRAMP
        Pattern {
            name: "fedramp".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)fedramp|federal\s*risk\s*and\s*authorization".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "FedRAMP reference detected".to_string(),
            reference: Some("https://www.fedramp.gov/".to_string()),
            tags: vec!["compliance".to_string(), "fedramp".to_string(), "government".to_string()],
            env_var: false,
            binary: false,
        },
        // CCPA patterns
        Pattern {
            name: "ccpa-reference".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)ccpa|california\s+consumer\s+privacy".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "CCPA reference detected".to_string(),
            reference: Some("https://oag.ca.gov/privacy/ccpa".to_string()),
            tags: vec!["compliance".to_string(), "ccpa".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "ccpa-consumer-rights".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)(right\s*to\s*know|right\s*to\s*delete|right\s*to\s*opt[-_]?out)".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CCPA consumer rights reference detected".to_string(),
            reference: Some("https://oag.ca.gov/privacy/ccpa".to_string()),
            tags: vec!["compliance".to_string(), "ccpa".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        // LGPD patterns
        Pattern {
            name: "lgpd".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)lgpd|lei\s*geral\s*de\s*proteção".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "LGPD (Brazilian GDPR) reference detected".to_string(),
            reference: Some("https://www.gov.br/cidadania/pt-br/acesso-a-informacao/lgpd".to_string()),
            tags: vec!["compliance".to_string(), "lgpd".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        // POPIA patterns
        Pattern {
            name: "popia".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)popia|protection\s*of\s*personal\s*information".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "POPIA (South Africa) reference detected".to_string(),
            reference: Some("https://popia.co.za/".to_string()),
            tags: vec!["compliance".to_string(), "popia".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        // PIPL (China)
        Pattern {
            name: "pipl".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)pipl|china\s*personal\s*information\s*protection".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "PIPL (China Personal Information Protection Law) reference detected".to_string(),
            reference: Some("http://www.npc.gov.cn/npc/c30834/202108/a8c4e3672c74491a80b53a172bb753fe.shtml".to_string()),
            tags: vec!["compliance".to_string(), "pipl".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        // HITRUST
        Pattern {
            name: "hitrust".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)hitrust|health\s*information\s*trust".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "HITRUST reference detected".to_string(),
            reference: Some("https://hitrustalliance.net/".to_string()),
            tags: vec!["compliance".to_string(), "hitrust".to_string(), "healthcare".to_string()],
            env_var: false,
            binary: false,
        },
        // COBIT
        Pattern {
            name: "cobit".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)cobit|control\s*objectives\s*for\s*information".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "COBIT reference detected".to_string(),
            reference: Some("https://www.isaca.org/resources/cobit".to_string()),
            tags: vec!["compliance".to_string(), "cobit".to_string(), "governance".to_string()],
            env_var: false,
            binary: false,
        },
        // COSO
        Pattern {
            name: "coso".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)coso|committee\s*of\s*sponsoring\s*organizations".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "COSO framework reference detected".to_string(),
            reference: Some("https://www.coso.org/".to_string()),
            tags: vec!["compliance".to_string(), "coso".to_string(), "governance".to_string()],
            env_var: false,
            binary: false,
        },
        // GLBA
        Pattern {
            name: "glba".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)glba|gramm[-_]?leach[-_]?bliley".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GLBA (Gramm-Leach-Bliley Act) reference detected".to_string(),
            reference: Some("https://www.ftc.gov/privacy/privacyinitiatives/glbact".to_string()),
            tags: vec!["compliance".to_string(), "glba".to_string(), "finance".to_string()],
            env_var: false,
            binary: false,
        },
        // FERPA
        Pattern {
            name: "ferpa".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)ferpa|family\s*educational\s*rights".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "FERPA reference detected".to_string(),
            reference: Some("https://www2.ed.gov/policy/gen/guid/fpco/ferpa/index.html".to_string()),
            tags: vec!["compliance".to_string(), "ferpa".to_string(), "education".to_string()],
            env_var: false,
            binary: false,
        },
        // COPPA
        Pattern {
            name: "coppa".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)coppa|children['\s]+online\s*privacy\s*protection".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "COPPA reference detected".to_string(),
            reference: Some("https://www.ftc.gov/legal-library/browse/rules/childrens-online-privacy-protection-rule-coppa".to_string()),
            tags: vec!["compliance".to_string(), "coppa".to_string(), "children".to_string()],
            env_var: false,
            binary: false,
        },
        // ISO 9001
        Pattern {
            name: "iso-9001".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)iso\s*9001|quality\s*management".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "ISO 9001 reference detected".to_string(),
            reference: Some("https://www.iso.org/iso-9001-quality-management.html".to_string()),
            tags: vec!["compliance".to_string(), "iso9001".to_string(), "quality".to_string()],
            env_var: false,
            binary: false,
        },
        // PCI PA-DSS
        Pattern {
            name: "pa-dss".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)pa[-_]?dss|payment\s*application\s*data\s*security".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PA-DSS reference detected".to_string(),
            reference: Some("https://www.pcisecuritystandards.org/".to_string()),
            tags: vec!["compliance".to_string(), "pa-dss".to_string(), "payment".to_string()],
            env_var: false,
            binary: false,
        },
        // Data residency
        Pattern {
            name: "data-residency".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)data\s*residency|data\s*sovereignty|data\s*localization".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Data residency requirement reference detected".to_string(),
            reference: None,
            tags: vec!["compliance".to_string(), "data-residency".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        // Data retention
        Pattern {
            name: "data-retention".to_string(),
            category: "compliance".to_string(),
            match_pattern: r"(?i)data\s*retention|record\s*retention|document\s*retention".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Data retention policy reference detected".to_string(),
            reference: None,
            tags: vec!["compliance".to_string(), "data-retention".to_string(), "records".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
