//! Cryptographic misuse patterns - weak primitives and broken constructions
//!
//! These rules flag objectively broken or deprecated cryptography: weak
//! hashes over passwords, ECB mode, legacy ciphers, predictable key
//! material, and timing-unsafe comparisons. Unlike the ai-detection
//! heuristics these are engineering defects with published guidance, so
//! severities run higher.

use crate::Pattern;

/// Cryptographic misuse rules.
#[must_use]
pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "crypto-weak-password-hash".to_string(),
            category: "cryptography".to_string(),
            match_pattern: r#"(?i)\b(?:md5|sha1)\s*\(\s*(?:password|passwd|pwd|pass|\$_?post\.)|\b(?:md5|sha1)\.hexdigest\s*\(\s*(?:password|passwd|pass)|createHash\s*\(\s*['\"](?:md5|sha1)['\"]\s*\)\.update\s*\(\s*(?:password|passwd|pwd|pass)|hashlib\.(?:md5|sha1)\s*\(\s*(?:password|passwd|pwd|pw|pass)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "MD5/SHA-1 used to hash a password; both are broken for password storage".to_string(),
            reference: Some("https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html".to_string()),
            tags: vec!["cryptography".to_string(), "hashing".to_string(), "passwords".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "crypto-weak-hmac".to_string(),
            category: "cryptography".to_string(),
            match_pattern: r#"(?i)\bHmac(?:MD5|SHA1)\b|createHmac\s*\(\s*['\"](?:md5|sha1)['\"]|hmac(?:_new)?\s*\(\s*['\"](?:md5|sha1)['\"]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "HMAC built on MD5 or SHA-1; use SHA-256 or stronger".to_string(),
            reference: Some("https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html".to_string()),
            tags: vec!["cryptography".to_string(), "mac".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "crypto-ecb-mode".to_string(),
            category: "cryptography".to_string(),
            match_pattern: r#"(?i)\baes[-_/]ecb\b|\bMODE_ECB\b|['\"]ECB['\"]|\bECBMode\b|NewECB(?:Encryptor|Decryptor)?\b"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "ECB mode selected; identical blocks encrypt identically and leak structure".to_string(),
            reference: Some("https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html".to_string()),
            tags: vec!["cryptography".to_string(), "cipher-mode".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "crypto-legacy-cipher".to_string(),
            category: "cryptography".to_string(),
            match_pattern: r#"(?i)\b(?:des-ecb|des-cbc|des-ede3?|3des|desede|rc4|arc4|arcfour|blowfish)\b|Crypto\.Cipher\.(?:DES|ARC4|Blowfish)|Cipher\.getInstance\s*\(\s*\"(?:DES|RC4)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Legacy cipher (DES, 3DES, RC4, Blowfish) referenced; all are deprecated".to_string(),
            reference: Some("https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html".to_string()),
            tags: vec!["cryptography".to_string(), "cipher".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "crypto-low-pbkdf2-iterations".to_string(),
            category: "cryptography".to_string(),
            match_pattern: r"(?i)pbkdf2(?:_hmac)?\s*\([^)]*?,\s*(?:\d{1,4}|1[0-4]\d{3})\s*[,)]|\biterations\s*[:=]\s*(?:\d{1,4}|1[0-4]\d{3})\b".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "PBKDF2 with fewer than 15000 iterations; below modern brute-force resistance".to_string(),
            reference: Some("https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html".to_string()),
            tags: vec!["cryptography".to_string(), "kdf".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "crypto-insecure-rsa-padding".to_string(),
            category: "cryptography".to_string(),
            match_pattern: r#"(?i)RSA/(?:ECB|NONE)/(?:PKCS1|NoPadding)|PKCS1_v1_5\.new\s*\(|padding\s*[:=]\s*['\"]?(?:NoPadding|PKCS1v15)['\";\s,]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "RSA encryption without OAEP padding; PKCS#1 v1.5 and no-padding are malleable".to_string(),
            reference: Some("https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html".to_string()),
            tags: vec!["cryptography".to_string(), "rsa".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "crypto-predictable-key-material".to_string(),
            category: "cryptography".to_string(),
            match_pattern: r"(?i)\b(?:key|nonce|salt|seed|secret|token)\w*\s*:?=\s*(?:Math\.random\s*\(\s*\)|random\.random\s*\(\s*\)|new\s+Random\s*\(\s*\)|rand::random\s*(?:::<[^>]*>)?\s*\(\s*\)|rand\.(?:Int|Intn|Float\d*)\s*\([^)]*\))".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Key, nonce, or seed derived from a non-cryptographic PRNG".to_string(),
            reference: Some("https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html".to_string()),
            tags: vec!["cryptography".to_string(), "randomness".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "crypto-zero-iv-or-nonce".to_string(),
            category: "cryptography".to_string(),
            match_pattern: r"(?i)\b(?:iv|nonce)\s*:?=[^;\n]*(?:make\s*\(\s*\[\]byte|new\s+byte\s*\[|Buffer\.alloc\s*\(|bytearray\s*\(|\[0(?:\s*,\s*0){5,}\]).*".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "IV or nonce allocated as all-zero bytes; fixed IVs break CBC/GCM security".to_string(),
            reference: Some("https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html".to_string()),
            tags: vec!["cryptography".to_string(), "iv".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "crypto-hardcoded-salt".to_string(),
            category: "cryptography".to_string(),
            match_pattern: r#"(?i)\bsalt\s*[:=]\s*['\"][a-zA-Z0-9_]{6,}['\"]"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Hard-coded salt string; salts should be random per credential".to_string(),
            reference: None,
            tags: vec!["cryptography".to_string(), "salt".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "crypto-timing-unsafe-compare".to_string(),
            category: "cryptography".to_string(),
            match_pattern: r"(?i)\b(?:mac|digest|signature|hmac|checksum)\w*\s*(?:===|==)\s*[A-Za-z_$].*".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "MAC or signature compared with == instead of a constant-time compare".to_string(),
            reference: Some("https://cwe.mitre.org/data/definitions/208.html".to_string()),
            tags: vec!["cryptography".to_string(), "timing".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
    ]
}
