//! Data visualization patterns

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "chart-accessibility".to_string(),
            category: "data_visualization".to_string(),
            match_pattern: r"canvas[^>]*[^aria-]|tooltip.*enabled.*false|legend.*display.*false".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Chart accessibility issue detected - missing ARIA attributes or disabled accessibility features".to_string(),
            reference: Some("https://chartjs.org/docs/latest/general/accessibility.html".to_string()),
            tags: vec!["chart".to_string(), "accessibility".to_string(), "a11y".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "chart-config".to_string(),
            category: "data_visualization".to_string(),
            match_pattern: r"Chart\.js.*type.*bar.*data.*1000\+|options.*responsive.*false|scale.*ticks.*display.*false".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Chart configuration issue detected - potential performance or display problem".to_string(),
            reference: Some("https://www.chartjs.org/docs/latest/configuration/".to_string()),
            tags: vec!["chart".to_string(), "configuration".to_string(), "performance".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "chart-types".to_string(),
            category: "data_visualization".to_string(),
            match_pattern: r"type.*bar.*data.*1000\+|type.*line.*categories.*10\+|type.*pie.*slices.*20\+".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Chart type mismatch detected - inappropriate chart type for data volume".to_string(),
            reference: Some("https://chartjs.org/docs/latest/charts/".to_string()),
            tags: vec!["chart".to_string(), "type".to_string(), "data-visualization".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "color-schemes".to_string(),
            category: "data_visualization".to_string(),
            match_pattern: r"backgroundColor.*#[fF]{6}|borderColor.*#[0F]{6}|color.*palette.*contrast".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Color scheme issue detected - invalid hex color format or poor contrast".to_string(),
            reference: Some("https://chartjs.org/docs/latest/axes/styling.html".to_string()),
            tags: vec!["chart".to_string(), "color".to_string(), "accessibility".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "mobile-optimization".to_string(),
            category: "data_visualization".to_string(),
            match_pattern: r"responsive.*false|width.*100%.*height.*100%|chart.*mobile.*breakpoint".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Mobile optimization issue detected - charts may not render properly on mobile devices".to_string(),
            reference: Some("https://chartjs.org/docs/latest/general/responsive.html".to_string()),
            tags: vec!["chart".to_string(), "mobile".to_string(), "responsive".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
