//! DevOps patterns - CI/CD, pipelines, deployment

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "ci-bypass".to_string(),
            category: "devops".to_string(),
            match_pattern: r"(?i)(bypass|skip|disable|ignore).*(ci|pipeline|check|test|lint)"
                .to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CI/CD bypass marker detected".to_string(),
            reference: None,
            tags: vec!["ci-cd".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hardcoded-ip".to_string(),
            category: "devops".to_string(),
            match_pattern: r"(?i)\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Hardcoded IP address detected".to_string(),
            reference: None,
            tags: vec![
                "ip".to_string(),
                "hardcoded".to_string(),
                "devops".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "debug-endpoint".to_string(),
            category: "devops".to_string(),
            match_pattern: r"(?i)(debug|test|dev|staging).*(endpoint|api|route)".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Debug/test endpoint detected".to_string(),
            reference: None,
            tags: vec!["endpoint".to_string(), "debug".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "docker-socket".to_string(),
            category: "devops".to_string(),
            match_pattern: r"(/var/run/docker\.sock|/run/docker\.sock)".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Docker socket reference detected".to_string(),
            reference: None,
            tags: vec!["docker".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubeconfig-reference".to_string(),
            category: "devops".to_string(),
            match_pattern: r"(\.kube/config|kubeconfig)".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes config reference detected".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "config".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "env-file-in-git".to_string(),
            category: "devops".to_string(),
            match_pattern: r"\.env(\.\w+)?".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: ".env file may be committed to git".to_string(),
            reference: None,
            tags: vec![
                "git".to_string(),
                "secrets".to_string(),
                "devops".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-state".to_string(),
            category: "devops".to_string(),
            match_pattern: r"terraform\.tfstate".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform state file detected".to_string(),
            reference: None,
            tags: vec!["terraform".to_string(), "infrastructure".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "ansible-vault".to_string(),
            category: "devops".to_string(),
            match_pattern: r"\$ANSIBLE_VAULT".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Ansible vault encrypted content detected".to_string(),
            reference: None,
            tags: vec!["ansible".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "ci-secret-hardcoded".to_string(),
            category: "devops".to_string(),
            match_pattern:
                r#"(?i)(gh_token|github_token|circle_token|jenkins_api).*['"][a-zA-Z0-9]{10,}"#
                    .to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(3.5),
            description: "Hardcoded CI/CD secret detected".to_string(),
            reference: None,
            tags: vec!["ci-cd".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerignore-missing".to_string(),
            category: "devops".to_string(),
            match_pattern: r"^\.dockerignore".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Dockerignore file reference detected".to_string(),
            reference: None,
            tags: vec!["docker".to_string(), "best-practice".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "privileged-container".to_string(),
            category: "devops".to_string(),
            match_pattern: r"(?i)(privileged|--privileged)".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Privileged container configuration detected".to_string(),
            reference: None,
            tags: vec![
                "docker".to_string(),
                "security".to_string(),
                "container".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "root-user".to_string(),
            category: "devops".to_string(),
            match_pattern: r"(?i)(USER\s+root|RUN\s+.*chmod.*0777)".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Root user in Dockerfile detected".to_string(),
            reference: None,
            tags: vec!["docker".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "secrets-in-dockerfile".to_string(),
            category: "devops".to_string(),
            match_pattern: r"(?i)(ARG|ENV).*SECRET|KEY|TOKEN|PASSWORD".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential secret in Dockerfile detected".to_string(),
            reference: None,
            tags: vec!["docker".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "exposed-port".to_string(),
            category: "devops".to_string(),
            match_pattern: r"EXPOSE\s+\d{2,5}".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Exposed port in Dockerfile detected".to_string(),
            reference: None,
            tags: vec!["docker".to_string(), "network".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "latest-tag".to_string(),
            category: "devops".to_string(),
            match_pattern: r":latest".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Using latest tag in Dockerfile".to_string(),
            reference: None,
            tags: vec!["docker".to_string(), "best-practice".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
