//! Finance patterns - financial data and payment information

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "aba-routing-number".to_string(),
            category: "finance".to_string(),
            match_pattern: r"(?i)routing[\s_-]*(number|num|no)?[\s:=]+\b[0-9]{9}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "ABA routing number detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/ABA_routing_transit_number".to_string()),
            tags: vec![
                "bank".to_string(),
                "routing".to_string(),
                "finance".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "finance-bitcoin-address".to_string(),
            category: "finance".to_string(),
            match_pattern: r"\b(?:bc1|[13])[a-zA-HJ-NP-Z0-9]{25,62}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Bitcoin address detected".to_string(),
            reference: Some("https://en.bitcoin.it/wiki/Address".to_string()),
            tags: vec![
                "bitcoin".to_string(),
                "cryptocurrency".to_string(),
                "wallet".to_string(),
            ],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "ethereum-address".to_string(),
            category: "finance".to_string(),
            match_pattern: r"\b0x[0-9a-fA-F]{40}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Ethereum address detected".to_string(),
            reference: Some("https://ethereum.org/en/developers/docs/accounts/".to_string()),
            tags: vec![
                "ethereum".to_string(),
                "cryptocurrency".to_string(),
                "wallet".to_string(),
            ],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "finance-iban".to_string(),
            category: "finance".to_string(),
            match_pattern: r"\b[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "IBAN (International Bank Account Number) detected".to_string(),
            reference: Some(
                "https://en.wikipedia.org/wiki/International_Bank_Account_Number".to_string(),
            ),
            tags: vec![
                "bank".to_string(),
                "iban".to_string(),
                "finance".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "stripe-publishable-key".to_string(),
            category: "finance".to_string(),
            match_pattern: r"\bpk_(?:live|test)_[0-9a-zA-Z]{24,}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Stripe publishable key detected".to_string(),
            reference: Some("https://stripe.com/docs/keys".to_string()),
            tags: vec![
                "stripe".to_string(),
                "payment".to_string(),
                "api-key".to_string(),
            ],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "swift-bic".to_string(),
            category: "finance".to_string(),
            match_pattern: r"(?i)\b(?:swift|bic)[\s:=]+[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?\b"
                .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "SWIFT/BIC code detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/ISO_9362".to_string()),
            tags: vec![
                "bank".to_string(),
                "swift".to_string(),
                "bic".to_string(),
                "finance".to_string(),
            ],
            env_var: false,
            binary: false,
        },
    ]
}
