//! Finance patterns - financial data and payment information
//!
//! Financial identifier shapes (ABA, IBAN, SWIFT/BIC, BTC and ETH addresses) plus
//! Stripe publishable keys. A match proves format only, so confirm the surrounding
//! context before treating it as leaked data.

use crate::Pattern;

/// Financial identifier formats and payment-provider key shapes.
#[must_use]
pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "aba-routing-number".to_string(),
            category: "finance".to_string(),
            match_pattern: r"(?i)routing[\s_-]*(number|num|no)?[\s:=]+\b[0-9]{9}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "ABA routing number detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/ABA_routing_transit_number".to_string()),
            tags: vec![
                "bank".to_string(),
                "routing".to_string(),
                "finance".to_string(),
            ],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "finance-bitcoin-address".to_string(),
            category: "finance".to_string(),
            match_pattern: r"\b(?:bc1|[13])[a-zA-HJ-NP-Z0-9]{25,62}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Bitcoin address detected".to_string(),
            reference: Some("https://en.bitcoin.it/wiki/Address".to_string()),
            tags: vec![
                "bitcoin".to_string(),
                "cryptocurrency".to_string(),
                "wallet".to_string(),
            ],
            env_var: true,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "ethereum-address".to_string(),
            category: "finance".to_string(),
            match_pattern: r"\b0x[0-9a-fA-F]{40}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            // A 42-char hex-body span holds at most 18 distinct characters,
            // capping entropy near 4.13 bits — anything higher makes the
            // rule unreachable.
            min_entropy: Some(3.5),
            description: "Ethereum address detected".to_string(),
            reference: Some("https://ethereum.org/en/developers/docs/accounts/".to_string()),
            tags: vec![
                "ethereum".to_string(),
                "cryptocurrency".to_string(),
                "wallet".to_string(),
            ],
            env_var: true,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "finance-iban".to_string(),
            category: "finance".to_string(),
            match_pattern: r"\b[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "IBAN (International Bank Account Number) detected".to_string(),
            reference: Some(
                "https://en.wikipedia.org/wiki/International_Bank_Account_Number".to_string(),
            ),
            tags: vec![
                "bank".to_string(),
                "iban".to_string(),
                "finance".to_string(),
            ],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "stripe-publishable-key".to_string(),
            category: "finance".to_string(),
            match_pattern: r"\bpk_(?:live|test)_[0-9a-zA-Z]{24,}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Stripe publishable key detected".to_string(),
            reference: Some("https://stripe.com/docs/keys".to_string()),
            tags: vec![
                "stripe".to_string(),
                "payment".to_string(),
                "api-key".to_string(),
            ],
            env_var: true,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "swift-bic".to_string(),
            category: "finance".to_string(),
            match_pattern: r"(?i)\b(?:swift|bic)[\s:=]+[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?\b"
                .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "SWIFT/BIC code detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/ISO_9362".to_string()),
            tags: vec![
                "bank".to_string(),
                "swift".to_string(),
                "bic".to_string(),
                "finance".to_string(),
            ],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "finance-float-money-field".to_string(),
            category: "finance".to_string(),
            match_pattern: r"(?i)\b(?:double|float)\s+(?:price|amount|balance|total|cost|fee|subtotal|salary|payment)s?\b|(?:price|amount|balance|total|cost|fee)s?\s*:\s*float\b".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Money held in a binary floating-point field; IEEE 754 cannot represent decimal currency exactly".to_string(),
            reference: Some("https://martinfowler.com/articles/quantity.html".to_string()),
            tags: vec!["finance".to_string(), "correctness".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "finance-tofixed-currency".to_string(),
            category: "finance".to_string(),
            match_pattern: r"(?i)\.toFixed\s*\(\s*[0-2]\s*\)".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "toFixed used for currency rounding; binary rounding still applies beneath the formatting".to_string(),
            reference: Some("https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed".to_string()),
            tags: vec!["finance".to_string(), "correctness".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "finance-math-round-money".to_string(),
            category: "finance".to_string(),
            match_pattern: r"(?i)Math\.round\s*\([^)]*(?:price|amount|total|balance|cost|fee|cent).*".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Math.round applied to a money value; banker's-rounding expectations differ".to_string(),
            reference: None,
            tags: vec!["finance".to_string(), "rounding".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "finance-float-equality".to_string(),
            category: "finance".to_string(),
            match_pattern: r"(?i)\b(?:price|amount|total|balance)\w*\s*(?:===|==)\s*[-+]?\d.*".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Money compared for exact equality; float residue makes this unreliable".to_string(),
            reference: None,
            tags: vec!["finance".to_string(), "correctness".to_string()],
            env_var: false,
            binary: false,
            exclude: Some(r"(?i)(?:_count|_findings|_items|_rows|_lines|_files|_records|_pages|_matches|_size|_length|_number|_num)\b".to_string()),
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "finance-parsefloat-money".to_string(),
            category: "finance".to_string(),
            match_pattern: r"(?i)parseFloat\s*\([^)]*(?:price|amount|total|balance|cost|fee).*".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Money parsed through parseFloat, inheriting binary float error".to_string(),
            reference: None,
            tags: vec!["finance".to_string(), "parsing".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "finance-balance-read-modify-write".to_string(),
            category: "finance".to_string(),
            match_pattern: r"(?i)\b(?:balance|available)\s*:?=\s*(?:\w+\.)?(?:balance|available)\s*[-+*].*".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Balance updated by read-modify-write; concurrent updates can lose money without locking".to_string(),
            reference: None,
            tags: vec!["finance".to_string(), "concurrency".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "finance-naive-settlement-now".to_string(),
            category: "finance".to_string(),
            match_pattern: r"(?i)\b(?:settlement|maturity|expiry|expires_at|effective)\w*\s*:?=\s*(?:new\s+Date\s*\(\s*\)|datetime\.now\s*\(\s*\)|Date\.now\s*\(\s*\)|LocalDate\.now\s*\(\s*\)).*".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Settlement or expiry timestamp taken from wall-clock now(); timezone and reproducibility hazard".to_string(),
            reference: None,
            tags: vec!["finance".to_string(), "time".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
    ]
}
