//! Framework-specific patterns

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        // Angular patterns
        Pattern {
            name: "angular-bypass-security-trust".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"\.bypassSecurityTrust(HTML|Url|Script|Style|ResourceUrl)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Angular security bypass detected. bypassSecurityTrust calls disable Angular's built-in XSS protection.".to_string(),
            reference: None,
            tags: vec!["angular".to_string(), "xss".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "angular-innerhtml-xss".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"\.innerHTML\s*="#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Angular innerHTML assignment detected. This can introduce XSS vulnerabilities.".to_string(),
            reference: None,
            tags: vec!["angular".to_string(), "xss".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        // Django patterns
        Pattern {
            name: "django-debug-print".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"(?i)(print\(.*request|DEBUG\s*=\s*True|django.*debug)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Debug code should be removed before production deployment.".to_string(),
            reference: None,
            tags: vec!["django".to_string(), "debug".to_string(), "python".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "django-csrf-exempt".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"@csrf_exempt\b"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Missing CSRF protection. Forms should include CSRF tokens.".to_string(),
            reference: None,
            tags: vec!["django".to_string(), "csrf".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "django-secret-key-hardcoded".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"\bSECRET_KEY\s*=\s*["\x27][^\x27"]{20,}["\x27]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Hardcoded Django SECRET_KEY detected. Use environment variables instead.".to_string(),
            reference: None,
            tags: vec!["django".to_string(), "secret".to_string(), "credential".to_string()],
            env_var: false,
            binary: false,
        },
        // Express patterns
        Pattern {
            name: "express-eval-usage".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"eval\s*\(.*(?:req|request|body|params|query)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Express.js eval() with user input detected. This can lead to remote code execution.".to_string(),
            reference: None,
            tags: vec!["express".to_string(), "nodejs".to_string(), "rce".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "express-sql-injection".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"(query|execute)\s*\(.*[\+\`].*\$\{"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Express.js SQL query with template literal interpolation detected. This can lead to SQL injection.".to_string(),
            reference: None,
            tags: vec!["express".to_string(), "nodejs".to_string(), "sql-injection".to_string()],
            env_var: false,
            binary: false,
        },
        // Flask patterns
        Pattern {
            name: "flask-debug-enabled".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"app\.run\s*\(\s*debug\s*=\s*True"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Flask debug mode enabled. This should be disabled in production.".to_string(),
            reference: None,
            tags: vec!["flask".to_string(), "python".to_string(), "debug".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "flask-sqlalchemy-raw-sql".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"(execute|raw_sql)\s*\(.*[%\#\{]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Flask-SQLAlchemy raw SQL with string interpolation detected. This can lead to SQL injection.".to_string(),
            reference: None,
            tags: vec!["flask".to_string(), "sqlalchemy".to_string(), "sql-injection".to_string()],
            env_var: false,
            binary: false,
        },
        // Go patterns
        Pattern {
            name: "go-defer-goroutine-leak".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"defer\s+go\s+"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "defer with goroutine may cause goroutine leak.".to_string(),
            reference: None,
            tags: vec!["go".to_string(), "goroutine".to_string(), "concurrency".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "go-json-marshal-error-ignore".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"json\.(Marshal|Unmarshal)\([^,)]+,\s*[^)]+\)\s*$"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "json.Marshal/Unmarshal result checked without error handling.".to_string(),
            reference: None,
            tags: vec!["go".to_string(), "json".to_string(), "error-handling".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "go-strconv-error-ignore".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"strconv\.(ParseInt|ParseUint|ParseFloat|ParseBool)\([^)]+\)[^\s]"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "strconv function result used without error check.".to_string(),
            reference: None,
            tags: vec!["go".to_string(), "strconv".to_string(), "error-handling".to_string()],
            env_var: false,
            binary: false,
        },
        // Laravel patterns
        Pattern {
            name: "laravel-app-key-hardcoded".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"APP_KEY\s*=\s*(base64:)?[a-zA-Z0-9\/+=]{32,}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Laravel APP_KEY hardcoded in source. This should be stored in environment variables.".to_string(),
            reference: None,
            tags: vec!["laravel".to_string(), "php".to_string(), "secret".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "laravel-raw-db-query".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"DB::(?:select|statement|unprepared)\s*\(.*["\'].*%s"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Laravel raw database query with string formatting detected. This can lead to SQL injection.".to_string(),
            reference: None,
            tags: vec!["laravel".to_string(), "php".to_string(), "sql-injection".to_string()],
            env_var: false,
            binary: false,
        },
        // NodeJS patterns
        Pattern {
            name: "nodejs-hardcoded-jwt-secret".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"\b(jwt\.sign|jsonwebtoken\.sign)\s*\(\s*[^,]+,\s*["\x27][A-Za-z0-9_\-]{16,}["\x27]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Hardcoded JWT secret detected. Use environment variables instead.".to_string(),
            reference: None,
            tags: vec!["nodejs".to_string(), "jwt".to_string(), "secret".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "nodejs-sync-fs-readfile".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"\bfs\.readFileSync\s*\("#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Synchronous file read detected. Use async version for better performance.".to_string(),
            reference: None,
            tags: vec!["nodejs".to_string(), "filesystem".to_string(), "performance".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "nodejs-todo-development".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"(?i)(console\.log.*todo|\/\/\s*TODO.*fixme|FIXME.*console\.log)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "TODO/FIXME comment detected. Pending tasks should be tracked in issue tracker.".to_string(),
            reference: None,
            tags: vec!["nodejs".to_string(), "code-quality".to_string(), "todo".to_string()],
            env_var: false,
            binary: false,
        },
        // Rails patterns
        Pattern {
            name: "rails-raw-sql-injection".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"\.execute\s*\(.*[#\{]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Rails raw SQL execution detected. This can lead to SQL injection.".to_string(),
            reference: None,
            tags: vec!["rails".to_string(), "ruby".to_string(), "sql-injection".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rails-secret-key-hardcoded".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"(secret_key_base|secret_token)\s*=\s*["'][a-f0-9]{64}["']"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Rails secret key hardcoded in source. Use environment variables.".to_string(),
            reference: None,
            tags: vec!["rails".to_string(), "ruby".to_string(), "secret".to_string()],
            env_var: false,
            binary: false,
        },
        // React patterns
        Pattern {
            name: "react-console-log-dev".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"(?i)(console\.log|console\.debug|console\.warn).*development|if.*process\.env\.NODE_ENV.*development"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Debug logging detected. Remove before production deployment.".to_string(),
            reference: None,
            tags: vec!["react".to_string(), "javascript".to_string(), "debug".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "react-missing-key-prop".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"\.\s*map\s*\([^)]*\)\s*=>\s*[<\(]"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "React map without key prop detected.".to_string(),
            reference: None,
            tags: vec!["react".to_string(), "javascript".to_string(), "jsx".to_string()],
            env_var: false,
            binary: false,
        },
        // Rust patterns
        Pattern {
            name: "rust-env-macro".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"env!\s*\("#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Rust env! macro detected. This will panic if environment variable is not set.".to_string(),
            reference: None,
            tags: vec!["rust".to_string(), "env".to_string(), "panic".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rust-expect-usage".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"\.expect\("#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Rust .expect() call detected. This can panic.".to_string(),
            reference: None,
            tags: vec!["rust".to_string(), "error-handling".to_string(), "panic".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rust-hardcoded-secret".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"(api_key|apiKey|secret|password|token|credential)\s*[:=]\s*["\'][^"\'\s]{8,}["\']"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Hardcoded secret detected in Rust code.".to_string(),
            reference: None,
            tags: vec!["rust".to_string(), "secret".to_string(), "credential".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rust-println-debug".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"println!\s*\(\s*"[^"]*\{:?\?:[^}]*\}[^"]*"\s*,"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Rust debug println! with formatting detected.".to_string(),
            reference: None,
            tags: vec!["rust".to_string(), "debug".to_string(), "println".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rust-unsafe-block".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"unsafe\s*\{[^}]*\}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Rust unsafe block detected. Bypasses memory safety guarantees.".to_string(),
            reference: None,
            tags: vec!["rust".to_string(), "unsafe".to_string(), "memory-safety".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rust-unsafe-extern".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"extern\s*"[^"]*"\s*\{"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Rust unsafe extern block detected.".to_string(),
            reference: None,
            tags: vec!["rust".to_string(), "unsafe".to_string(), "ffi".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rust-unwrap-usage".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"\.unwrap\(\)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Rust .unwrap() call detected. This can panic.".to_string(),
            reference: None,
            tags: vec!["rust".to_string(), "error-handling".to_string(), "panic".to_string()],
            env_var: false,
            binary: false,
        },
        // Spring pattern
        Pattern {
            name: "spring-deserialization-readObject".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"(ObjectInputStream|readObject)\s*\(\s*\)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Java deserialization detected. Unsafe deserialization can lead to RCE.".to_string(),
            reference: None,
            tags: vec!["spring".to_string(), "java".to_string(), "deserialization".to_string()],
            env_var: false,
            binary: false,
        },
        // Vue patterns
        Pattern {
            name: "vue-v-html-xss".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#"v-html=["'][^"']{10,}["']"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Vue.js v-html directive detected. This can introduce XSS vulnerabilities.".to_string(),
            reference: None,
            tags: vec!["vue".to_string(), "xss".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "vue-template-injection".to_string(),
            category: "frameworks".to_string(),
            match_pattern: r#":[a-z]+=["'][^"]*request|:[a-z]+=["'][^"]*input|:[a-z]+=["'][^"]*params"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Vue.js template injection detected.".to_string(),
            reference: None,
            tags: vec!["vue".to_string(), "template-injection".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
