//! Git hygiene patterns - commit quality, branch naming, conflict detection

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "merge-conflict".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r"^<{7}|^={7}|^>{7}".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Unresolved merge conflict marker detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging".to_string()),
            tags: vec!["git".to_string(), "merge-conflict".to_string(), "hygiene".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-commit-signoff".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"Signed-off-by:"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Git sign-off detected (DCO)".to_string(),
            reference: Some("https://developercertificate.org/".to_string()),
            tags: vec!["git".to_string(), "commit".to_string(), "signoff".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-commit-verify".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"gpg.sign\s*=\s*true"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GPG commit signing enabled".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work".to_string()),
            tags: vec!["git".to_string(), "gpg".to_string(), "signing".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gitignore-entry".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^\.gitignore$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: ".gitignore file detected".to_string(),
            reference: Some("https://git-scm.com/docs/gitignore".to_string()),
            tags: vec!["git".to_string(), "gitignore".to_string(), "hygiene".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gitattributes-entry".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^\.gitattributes$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: ".gitattributes file detected".to_string(),
            reference: Some("https://git-scm.com/docs/gitattributes".to_string()),
            tags: vec!["git".to_string(), "gitattributes".to_string(), "hygiene".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gitmodules-entry".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^\.gitmodules$"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: ".gitmodules file detected (git submodule)".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Tools-Submodules".to_string()),
            tags: vec!["git".to_string(), "submodule".to_string(), "hygiene".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "commit-message-conventional".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"(?i)^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert)\([^)]+\):"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Conventional commit message format detected".to_string(),
            reference: Some("https://www.conventionalcommits.org/".to_string()),
            tags: vec!["git".to_string(), "commit".to_string(), "conventional".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "branch-naming-feature".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^feature/[a-z0-9-_]+$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Feature branch naming convention detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows".to_string()),
            tags: vec!["git".to_string(), "branch".to_string(), "naming".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "branch-naming-bugfix".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^bugfix/[a-z0-9-_]+$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Bugfix branch naming convention detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows".to_string()),
            tags: vec!["git".to_string(), "branch".to_string(), "naming".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "branch-naming-hotfix".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^hotfix/[a-z0-9-_]+$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Hotfix branch naming convention detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows".to_string()),
            tags: vec!["git".to_string(), "branch".to_string(), "naming".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "branch-naming-release".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^release/[a-z0-9._-]+$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Release branch naming convention detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows".to_string()),
            tags: vec!["git".to_string(), "branch".to_string(), "naming".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "commit-sha-reference".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"\b[0-9a-f]{40}\b"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Full commit SHA reference detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection".to_string()),
            tags: vec!["git".to_string(), "commit".to_string(), "sha".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "merge-commit".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^Merge branch"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Merge commit message detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging".to_string()),
            tags: vec!["git".to_string(), "merge".to_string(), "commit".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "tag-reference".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^refs/tags/v?\d+\.\d+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Semantic version tag reference detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Basics-Tagging".to_string()),
            tags: vec!["git".to_string(), "tag".to_string(), "version".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
