//! Git hygiene patterns - commit quality, branch naming, conflict detection

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "merge-conflict".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^<{7}|^={7}|^>{7}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Unresolved merge conflict marker detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging".to_string()),
            tags: vec!["git".to_string(), "merge-conflict".to_string(), "hygiene".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-commit-signoff".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"Signed-off-by:"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Git sign-off detected (DCO)".to_string(),
            reference: Some("https://developercertificate.org/".to_string()),
            tags: vec!["git".to_string(), "commit".to_string(), "signoff".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-commit-verify".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"gpg.sign\s*=\s*true"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GPG commit signing enabled".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work".to_string()),
            tags: vec!["git".to_string(), "gpg".to_string(), "signing".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gitignore-entry".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^\.gitignore$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: ".gitignore file detected".to_string(),
            reference: Some("https://git-scm.com/docs/gitignore".to_string()),
            tags: vec!["git".to_string(), "gitignore".to_string(), "hygiene".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gitattributes-entry".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^\.gitattributes$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: ".gitattributes file detected".to_string(),
            reference: Some("https://git-scm.com/docs/gitattributes".to_string()),
            tags: vec!["git".to_string(), "gitattributes".to_string(), "hygiene".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gitmodules-entry".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^\.gitmodules$"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: ".gitmodules file detected (git submodule)".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Tools-Submodules".to_string()),
            tags: vec!["git".to_string(), "submodule".to_string(), "hygiene".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "commit-message-conventional".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"(?i)^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert)\([^)]+\):"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Conventional commit message format detected".to_string(),
            reference: Some("https://www.conventionalcommits.org/".to_string()),
            tags: vec!["git".to_string(), "commit".to_string(), "conventional".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "branch-naming-feature".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^feature/[a-z0-9-_]+$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Feature branch naming convention detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows".to_string()),
            tags: vec!["git".to_string(), "branch".to_string(), "naming".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "branch-naming-bugfix".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^bugfix/[a-z0-9-_]+$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Bugfix branch naming convention detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows".to_string()),
            tags: vec!["git".to_string(), "branch".to_string(), "naming".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "branch-naming-hotfix".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^hotfix/[a-z0-9-_]+$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Hotfix branch naming convention detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows".to_string()),
            tags: vec!["git".to_string(), "branch".to_string(), "naming".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "branch-naming-release".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^release/[a-z0-9._-]+$"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Release branch naming convention detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows".to_string()),
            tags: vec!["git".to_string(), "branch".to_string(), "naming".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "commit-sha-reference".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"\b[0-9a-f]{40}\b"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Full commit SHA reference detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection".to_string()),
            tags: vec!["git".to_string(), "commit".to_string(), "sha".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "merge-commit".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^Merge branch"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Merge commit message detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging".to_string()),
            tags: vec!["git".to_string(), "merge".to_string(), "commit".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "tag-reference".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"^refs/tags/v?\d+\.\d+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Semantic version tag reference detected".to_string(),
            reference: Some("https://git-scm.com/book/en/v2/Git-Basics-Tagging".to_string()),
            tags: vec!["git".to_string(), "tag".to_string(), "version".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-hygiene-github-actions-workflow".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"\.github/workflows/[^/]+\.ya?ml"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GitHub Actions workflow detected".to_string(),
            reference: Some("https://docs.github.com/en/actions/learn-github-actions".to_string()),
            tags: vec!["github".to_string(), "ci-cd".to_string(), "workflow".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-hygiene-dependabot-config".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"dependabot\.yml"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dependabot configuration detected".to_string(),
            reference: Some("https://docs.github.com/en/code-security/dependabot".to_string()),
            tags: vec!["dependabot".to_string(), "dependencies".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-hygiene-renovate-config".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"renovate\.json"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Renovate configuration detected".to_string(),
            reference: Some("https://docs.renovatebot.com/".to_string()),
            tags: vec!["renovate".to_string(), "dependencies".to_string(), "automation".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "commitizen-config".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"\.(czrc|cz.json|commitizen)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Commitizen configuration detected".to_string(),
            reference: Some("https://commitizen-tools.github.io/commitizen/".to_string()),
            tags: vec!["commitizen".to_string(), "commit".to_string(), "convention".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "semantic-release-config".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"\.releaserc|semantic-release"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Semantic release configuration detected".to_string(),
            reference: Some("https://semantic-release.gitbook.io/semantic-release/".to_string()),
            tags: vec!["semantic-release".to_string(), "release".to_string(), "automation".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-flow-model".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"(?i)git.flow|gitflow"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Git Flow branching model reference".to_string(),
            reference: Some("https://nvie.com/posts/a-successful-git-branching-model/".to_string()),
            tags: vec!["git".to_string(), "git-flow".to_string(), "branching".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "github-issue-reference".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"(?i)(fixes|closes|resolves)\s+#\d+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GitHub issue reference in commit".to_string(),
            reference: Some("https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue".to_string()),
            tags: vec!["github".to_string(), "issue".to_string(), "commit".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-hooks-husky".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"\.husky/"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Husky git hooks directory detected".to_string(),
            reference: Some("https://typicode.github.io/husky/".to_string()),
            tags: vec!["husky".to_string(), "git-hooks".to_string(), "automation".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "pre-commit-config".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"\.pre-commit-config\.ya?ml"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Pre-commit configuration detected".to_string(),
            reference: Some("https://pre-commit.com/".to_string()),
            tags: vec!["pre-commit".to_string(), "git-hooks".to_string(), "quality".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-worktree".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"git\s+worktree"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Git worktree command detected".to_string(),
            reference: Some("https://git-scm.com/docs/git-worktree".to_string()),
            tags: vec!["git".to_string(), "worktree".to_string(), "branching".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-stash".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"git\s+stash"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Git stash command detected".to_string(),
            reference: Some("https://git-scm.com/docs/git-stash".to_string()),
            tags: vec!["git".to_string(), "stash".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "git-lfs".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"git\s+lfs|\.gitattributes.*lfs"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Git LFS usage detected".to_string(),
            reference: Some("https://git-lfs.github.com/".to_string()),
            tags: vec!["git".to_string(), "lfs".to_string(), "storage".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "force-push-detected".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"(?i)git\s+push\s+--force|git\s+push\s+-f"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Force push command detected".to_string(),
            reference: None,
            tags: vec!["git".to_string(), "force-push".to_string(), "dangerous".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "commit-ampersand".to_string(),
            category: "git-hygiene".to_string(),
            match_pattern: r#"\bamp\b"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Commit message contains '&' instead of 'and'".to_string(),
            reference: None,
            tags: vec!["git".to_string(), "commit-message".to_string(), "style".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
