//! Healthcare patterns

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "clinical-trial-id".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r#"\bNCT[0-9]{8}\b"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Clinical trial identifier detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "clinical-trial".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "healthcare-code".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r#"\b(?:CPT|HCPCS|ICD-10)[A-Z0-9]{5,8}\b"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Healthcare code detected (CPT, HCPCS, ICD-10)".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "medical-code".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "insurance-number".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r#"\b(?:INS|INSURANCE)[0-9]{9,11}\b"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Insurance number detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "insurance".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "medical-license-number".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r#"\b(?:MD|DO|RN|LPN|PA|NP)[0-9]{8,12}\b"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Medical license number detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "license".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "medical-record-number".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r#"\bMRN[0-9]{8,12}\b"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Medical record number detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "medical-record".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "patient-id".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r#"\b(?:PATIENT|PT)[0-9]{8,12}\b"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Patient identifier detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "patient".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "prescription-number".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r#"\bRX[0-9]{7,10}\b"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Prescription number detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "prescription".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
