//! Healthcare patterns
//!
//! Clinical and payer identifiers (medical record, patient, prescription,
//! insurance, license, provider, and prescriber numbers) plus PHI-handling
//! hazards: identifiers alone say a file contains PHI, while the handling
//! rules flag the HIPAA technical-safeguard failures — PHI in logs, hard-coded
//! patient literals, plaintext transport, unencrypted storage flags, and
//! minimum-necessary violations — that turn contained PHI into exposed PHI.

use crate::Pattern;

/// Healthcare identifiers and PHI-handling hazards.
#[must_use]
pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "clinical-trial-id".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"\bNCT[0-9]{8}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Clinical trial identifier detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "clinical-trial".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "healthcare-code".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"\b(?:CPT|HCPCS|ICD-10)[A-Z0-9]{5,8}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Healthcare code detected (CPT, HCPCS, ICD-10)".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "medical-code".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "insurance-number".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"\b(?:INS|INSURANCE)[0-9]{9,11}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Insurance number detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "insurance".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "medical-license-number".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"\b(?:MD|DO|RN|LPN|PA|NP)[0-9]{8,12}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Medical license number detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "license".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "healthcare-medical-record-number".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"\bMRN[0-9]{8,12}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Medical record number detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "medical-record".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "patient-id".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"\b(?:PATIENT|PT)[0-9]{8,12}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Patient identifier detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "patient".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "healthcare-prescription-number".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"\bRX[0-9]{7,10}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Prescription number detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "prescription".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "national-provider-identifier".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"(?i)\bNPI[:\s#=-]*[0-9]{10}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "National Provider Identifier detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "provider".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "dea-number".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"(?i)\bDEA[:\s#=-]*[A-Z]{2}[0-9]{7}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "DEA prescriber registration number detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "prescriber".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "medicare-beneficiary-identifier".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"(?i)\b(?:MBI|HICN|MCR)[:\s#=-]*[0-9][A-Z0-9]{9,10}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Medicare beneficiary identifier (MBI/HICN) detected".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "medicare".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "healthcare-phi-logged".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"(?i)(?:\blog(?:ger|ging)?\s*[\.\(:_]|print(?:ln|f)?\s*\(|console\.(?:log|info|warn|error)\s*\(|dbg!|echo\s)[^\n;]{0,80}(?:\bpatient|\bmrn\b|\bdiagnos|\bmedical[_ ]?record|\bphi\b).*".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "PHI appears in a log or print statement; protected health information must not reach application logs".to_string(),
            reference: Some("https://www.hhs.gov/hipaa/for-professionals/security/guidance/security-rule-guidance/index.html".to_string()),
            tags: vec!["healthcare".to_string(), "phi".to_string(), "logging".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "healthcare-phi-hardcoded".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r#"(?i)\b(?:patient[_ ]?(?:name|id|address|phone|dob|email)|medical[_ ]?record|mrn|diagnosis)\w*\s*[:=]{1,2}\s*["\x27][^"\x27]{3,}["\x27]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Hard-coded patient identifier literal; PHI belongs in systems of record, not source control".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "phi".to_string(), "hardcoded".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "healthcare-phi-plaintext-endpoint".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r#"(?i)["\x27]http://[^"\x27\s]*(?:patient|medical|clinical|phi|health)[^"\x27\s]*["\x27]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Patient or clinical resource referenced over plaintext HTTP; PHI in transit requires encryption".to_string(),
            reference: Some("https://www.hhs.gov/hipaa/for-professionals/security/guidance/cybersecurity/index.html".to_string()),
            tags: vec!["healthcare".to_string(), "phi".to_string(), "transport".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "healthcare-phi-emailed".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r#"(?i)(?:(?:mailto:[^\s"\x27]*(?:patient|mrn|medical))|(?:send_?mail\s*\([^)]{0,80}(?:\bpatient|\bmrn|\bdiagnos|\bmedical))).*"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "PHI routed through email; unsecured email is a leading cause of reported healthcare breaches".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "phi".to_string(), "email".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "healthcare-select-star-phi-table".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"(?i)select\s+\*\s+from\s+(?:patients?|medical_\w+|health_?\w+|clinical_\w+|encounters?|diagnos\w+|prescriptions?|medications?|claims)\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "SELECT * over a PHI table; the minimum-necessary standard calls for selecting only required columns".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "phi".to_string(), "minimum-necessary".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "healthcare-phi-in-url-query".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r#"(?i).*[?&](?:patient(?:_id)?|mrn|ssn|dob|medical[_ ]?record)[a-z_]*=[^&"\x27\s]+"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Patient identifier in a URL query string; URLs persist in history, referrers, and access logs".to_string(),
            reference: None,
            tags: vec!["healthcare".to_string(), "phi".to_string(), "url".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
        Pattern {
            name: "healthcare-encryption-disabled".to_string(),
            category: "healthcare".to_string(),
            match_pattern: r"(?i)(?:\bphi\b|patient|medical)[\w\s,()\[\].-]{0,40}\bencrypt\w*\s*[:=]{1,2}\s*(?:false|0|no|none)\b|encrypt\w*\s*[:=]{1,2}\s*(?:false|0|no|none)\b[\w\s,()\[\].-]{0,40}(?:\bphi\b|patient|medical)".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Encryption explicitly disabled near patient or PHI data; addressable encryption is expected at rest".to_string(),
            reference: Some("https://www.hhs.gov/hipaa/for-professionals/security/guidance/encryption/index.html".to_string()),
            tags: vec!["healthcare".to_string(), "phi".to_string(), "encryption".to_string()],
            env_var: false,
            binary: false,
            exclude: None,
            file_extensions: Vec::new(),
        },
    ]
}
