//! Infrastructure patterns - Terraform, Kubernetes, Docker, CloudFormation

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        // Terraform patterns
        Pattern {
            name: "terraform-resource".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)resource\s+"[^"]+""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform resource definition detected".to_string(),
            reference: Some("https://developer.hashicorp.com/terraform/language/resources".to_string()),
            tags: vec!["terraform".to_string(), "iac".to_string(), "infrastructure".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-variable".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)variable\s+"[^"]+""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform variable definition detected".to_string(),
            reference: Some("https://developer.hashicorp.com/terraform/language/values/variables".to_string()),
            tags: vec!["terraform".to_string(), "iac".to_string(), "variable".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-output".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)output\s+"[^"]+""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform output definition detected".to_string(),
            reference: Some("https://developer.hashicorp.com/terraform/language/values/outputs".to_string()),
            tags: vec!["terraform".to_string(), "iac".to_string(), "output".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-backend".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)backend\s+"[^"]+""#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform backend configuration detected".to_string(),
            reference: Some("https://developer.hashicorp.com/terraform/language/settings/backends/configuration".to_string()),
            tags: vec!["terraform".to_string(), "iac".to_string(), "backend".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-sensitive-variable".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)sensitive\s*=\s*true"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform sensitive variable detected".to_string(),
            reference: Some("https://developer.hashicorp.com/terraform/language/values/variables#suppressing-values-in-cli-output".to_string()),
            tags: vec!["terraform".to_string(), "iac".to_string(), "sensitive".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-provider-aws".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"provider\s+"aws""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "AWS provider declaration detected".to_string(),
            reference: Some("https://registry.terraform.io/providers/hashicorp/aws/latest/docs".to_string()),
            tags: vec!["terraform".to_string(), "aws".to_string(), "provider".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-provider-azure".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"provider\s+"azurerm""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Azure provider declaration detected".to_string(),
            reference: Some("https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs".to_string()),
            tags: vec!["terraform".to_string(), "azure".to_string(), "provider".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-provider-gcp".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"provider\s+"google""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GCP provider declaration detected".to_string(),
            reference: Some("https://registry.terraform.io/providers/hashicorp/google/latest/docs".to_string()),
            tags: vec!["terraform".to_string(), "gcp".to_string(), "provider".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-module".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)module\s+"[^"]+""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform module usage detected".to_string(),
            reference: Some("https://developer.hashicorp.com/terraform/language/modules".to_string()),
            tags: vec!["terraform".to_string(), "iac".to_string(), "module".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-data-source".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)data\s+"[^"]+""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform data source detected".to_string(),
            reference: Some("https://developer.hashicorp.com/terraform/language/data-sources".to_string()),
            tags: vec!["terraform".to_string(), "iac".to_string(), "data".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-locals".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)locals\s*\{"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform locals block detected".to_string(),
            reference: Some("https://developer.hashicorp.com/terraform/language/values/locals".to_string()),
            tags: vec!["terraform".to_string(), "iac".to_string(), "locals".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-dynamic-block".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)dynamic\s+"[^"]+""#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform dynamic block detected".to_string(),
            reference: Some("https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks".to_string()),
            tags: vec!["terraform".to_string(), "iac".to_string(), "dynamic".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-for-each".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)for_each\s*="#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform for_each detected".to_string(),
            reference: Some("https://developer.hashicorp.com/terraform/language/meta-arguments/for_each".to_string()),
            tags: vec!["terraform".to_string(), "iac".to_string(), "for-each".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "terraform-count".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)count\s*="#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform count detected".to_string(),
            reference: Some("https://developer.hashicorp.com/terraform/language/meta-arguments/count".to_string()),
            tags: vec!["terraform".to_string(), "iac".to_string(), "count".to_string()],
            env_var: false,
            binary: false,
        },
        // Kubernetes patterns
        Pattern {
            name: "kubernetes-deployment".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*Deployment"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes Deployment detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/workloads/controllers/deployment/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "deployment".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-service".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*Service"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes Service detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/services-networking/service/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "service".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-configmap".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*ConfigMap"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes ConfigMap detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/configuration/configmap/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "configmap".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-secret".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*Secret"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes Secret detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/configuration/secret/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "secret".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-ingress".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*Ingress"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes Ingress detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/services-networking/ingress/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "ingress".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-pod".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*Pod"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes Pod detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/workloads/pods/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "pod".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-statefulset".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*StatefulSet"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes StatefulSet detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "statefulset".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-daemonset".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*DaemonSet"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes DaemonSet detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "daemonset".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-job".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*Job"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes Job detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/workloads/controllers/job/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "job".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-cronjob".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*CronJob"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes CronJob detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "cronjob".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-persistentvolume".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*PersistentVolume"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes PersistentVolume detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/storage/persistent-volumes/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "persistence".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-namespace".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*Namespace"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes Namespace detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "namespace".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-serviceaccount".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*ServiceAccount"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes ServiceAccount detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/security/service-accounts/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "serviceaccount".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-role".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*Role"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes Role detected".to_string(),
            reference: Some("https://kubernetes.io/docs/reference/access-authn-authz/rbac/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "rbac".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-clusterrole".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*ClusterRole"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes ClusterRole detected".to_string(),
            reference: Some("https://kubernetes.io/docs/reference/access-authn-authz/rbac/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "rbac".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-networkpolicy".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*NetworkPolicy"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes NetworkPolicy detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/services-networking/network-policies/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "network".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-resource-quota".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*ResourceQuota"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes ResourceQuota detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/policy/resource-quotas/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "quota".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-limitrange".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*LimitRange"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes LimitRange detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/policy/limit-range/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "limits".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-hpa".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*HorizontalPodAutoscaler"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes HPA detected".to_string(),
            reference: Some("https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "autoscaling".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-pdb".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*PodDisruptionBudget"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes PodDisruptionBudget detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/workloads/pods/disruptions/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "pdb".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "kubernetes-priorityclass".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)kind:\s*PriorityClass"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Kubernetes PriorityClass detected".to_string(),
            reference: Some("https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/".to_string()),
            tags: vec!["kubernetes".to_string(), "k8s".to_string(), "priority".to_string()],
            env_var: false,
            binary: false,
        },
        // Docker patterns
        Pattern {
            name: "dockerfile-from".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)^FROM\s+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dockerfile FROM instruction detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#from".to_string()),
            tags: vec!["docker".to_string(), "dockerfile".to_string(), "container".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerfile-run".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)^RUN\s+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dockerfile RUN instruction detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#run".to_string()),
            tags: vec!["docker".to_string(), "dockerfile".to_string(), "run".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerfile-cmd".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)^CMD\s+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dockerfile CMD instruction detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#cmd".to_string()),
            tags: vec!["docker".to_string(), "dockerfile".to_string(), "cmd".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerfile-expose".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)^EXPOSE\s+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dockerfile EXPOSE instruction detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#expose".to_string()),
            tags: vec!["docker".to_string(), "dockerfile".to_string(), "network".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerfile-env".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)^ENV\s+"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dockerfile ENV instruction detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#env".to_string()),
            tags: vec!["docker".to_string(), "dockerfile".to_string(), "env".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerfile-add".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)^ADD\s+"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dockerfile ADD instruction detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#add".to_string()),
            tags: vec!["docker".to_string(), "dockerfile".to_string(), "add".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerfile-copy".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)^COPY\s+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dockerfile COPY instruction detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#copy".to_string()),
            tags: vec!["docker".to_string(), "dockerfile".to_string(), "copy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerfile-workdir".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)^WORKDIR\s+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dockerfile WORKDIR instruction detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#workdir".to_string()),
            tags: vec!["docker".to_string(), "dockerfile".to_string(), "workdir".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerfile-volume".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)^VOLUME\s+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dockerfile VOLUME instruction detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#volume".to_string()),
            tags: vec!["docker".to_string(), "dockerfile".to_string(), "volume".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerfile-user".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)^USER\s+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dockerfile USER instruction detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#user".to_string()),
            tags: vec!["docker".to_string(), "dockerfile".to_string(), "user".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dockerfile-healthcheck".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)^HEALTHCHECK\s+"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dockerfile HEALTHCHECK instruction detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#healthcheck".to_string()),
            tags: vec!["docker".to_string(), "dockerfile".to_string(), "healthcheck".to_string()],
            env_var: false,
            binary: false,
        },
        // CloudFormation patterns
        Pattern {
            name: "cloudformation-resources".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)Resources:"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CloudFormation Resources section detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html".to_string()),
            tags: vec!["cloudformation".to_string(), "aws".to_string(), "infrastructure".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "cloudformation-parameters".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)Parameters:"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CloudFormation Parameters section detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html".to_string()),
            tags: vec!["cloudformation".to_string(), "aws".to_string(), "parameters".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "cloudformation-mappings".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)Mappings:"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CloudFormation Mappings section detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html".to_string()),
            tags: vec!["cloudformation".to_string(), "aws".to_string(), "mappings".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "cloudformation-outputs".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)Outputs:"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CloudFormation Outputs section detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html".to_string()),
            tags: vec!["cloudformation".to_string(), "aws".to_string(), "outputs".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "cloudformation-conditions".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"(?i)Conditions:"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CloudFormation Conditions section detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html".to_string()),
            tags: vec!["cloudformation".to_string(), "aws".to_string(), "conditions".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "cloudformationAWSTemplateFormatVersion".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"AWSTemplateFormatVersion:"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CloudFormation template version detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-version.html".to_string()),
            tags: vec!["cloudformation".to_string(), "aws".to_string(), "version".to_string()],
            env_var: false,
            binary: false,
        },
        // Helm charts
        Pattern {
            name: "helm-chart".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"apiVersion:\s*v2"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Helm Chart detected (apiVersion v2)".to_string(),
            reference: Some("https://helm.sh/docs/topics/charts/".to_string()),
            tags: vec!["helm".to_string(), "kubernetes".to_string(), "charts".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "helm-values".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"^values:"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Helm values file detected".to_string(),
            reference: Some("https://helm.sh/docs/chart_best_practices/values/".to_string()),
            tags: vec!["helm".to_string(), "kubernetes".to_string(), "values".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "helm-templates".to_string(),
            category: "infrastructure".to_string(),
            match_pattern: r#"templates/[^/]+\.ya?ml"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Helm template file detected".to_string(),
            reference: Some("https://helm.sh/docs/chart_template_guide/".to_string()),
            tags: vec!["helm".to_string(), "kubernetes".to_string(), "templates".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
