//! Kubernetes patterns

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "k8s-allow-privilege-escalation".to_string(),
            category: "kubernetes".to_string(),
            match_pattern: r#"allowPrivilegeEscalation:\s*(true|null)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Container allows privilege escalation".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "k8s-empty-dir-memory-backed".to_string(),
            category: "kubernetes".to_string(),
            match_pattern: r#"emptyDir:\s*\n\s*medium:\s*Memory"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "EmptyDir volume uses memory-backed storage".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "security".to_string(), "resource".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hostnetwork".to_string(),
            category: "kubernetes".to_string(),
            match_pattern: r#"(?i)securityContext:\s*\n\s*hostNetwork:\s*true"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Pod uses host network".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "security".to_string(), "network".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hostpid".to_string(),
            category: "kubernetes".to_string(),
            match_pattern: r#"(?i)securityContext:\s*\n\s*hostPID:\s*true"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Pod uses host PID namespace".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "security".to_string(), "process".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "latest-tag".to_string(),
            category: "kubernetes".to_string(),
            match_pattern: r#"(?i)image:\s*[^:\n]+:latest"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Container image uses latest tag".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "security".to_string(), "image".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "k8s-missing-capability-drop".to_string(),
            category: "kubernetes".to_string(),
            match_pattern: r#"securityContext"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Security context defined but missing capability drop".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "security".to_string(), "capabilities".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "k8s-no-network-policy".to_string(),
            category: "kubernetes".to_string(),
            match_pattern: r#"(NetworkPolicy|networkPolicy).*:\s*\|?\s*-\s*\{"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "No network policy defined for namespace".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "security".to_string(), "network".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "no-resource-limits".to_string(),
            category: "kubernetes".to_string(),
            match_pattern: r#"(?i)(containers:|-\s+name:).*?(image:|containers:)|resources:\s*\n\s*limits:"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Container has no resource limits defined".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "security".to_string(), "resource".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "privileged-container".to_string(),
            category: "kubernetes".to_string(),
            match_pattern: r#"(?i)securityContext:\s*\n\s*privileged:\s*true"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Container runs in privileged mode".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "security".to_string(), "privileged".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "k8s-run-as-non-root".to_string(),
            category: "kubernetes".to_string(),
            match_pattern: r#"(runAsNonRoot|runAsRoot):\s*(true|false)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Container run as root or missing runAsNonRoot configuration".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "security".to_string(), "root".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "secrets-in-manifest".to_string(),
            category: "kubernetes".to_string(),
            match_pattern: r#"(?i)(apiVersion:\s*v1\s*\n\s*kind:\s*Secret|secretKeyRef|data:\s*\n\s*  [a-zA-Z_]+:\s*['\"][^'\"]+['\"])"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Secrets may be exposed in Kubernetes manifests".to_string(),
            reference: None,
            tags: vec!["kubernetes".to_string(), "security".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
