//! LLM guardrails patterns - AI safety, content filtering, prompt injection

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "harmful-content-marker".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern:
                r#"(?i)(harmful|illegal|malicious|attack|exploit)\s+(content|instruct|guide)"#
                    .to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential harmful content marker detected".to_string(),
            reference: Some("https://platform.openai.com/docs/guides/moderation".to_string()),
            tags: vec![
                "llm-guardrails".to_string(),
                "safety".to_string(),
                "content-filter".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "pii-leak-risk".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern:
                r#"(?i)(extract|leak|share)\s+(personal|private|confidential)\s+(data|information)"#
                    .to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential PII leak instruction detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "pii".to_string(),
                "safety".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "llm-guardrails-prompt-injection".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(ignore|disregard|bypass)\s+(previous|above|initial|system)"#
                .to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Potential prompt injection attempt".to_string(),
            reference: Some("https://www.promptguard.com/".to_string()),
            tags: vec![
                "llm-guardrails".to_string(),
                "prompt-injection".to_string(),
                "security".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "system-prompt-override".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(system\s*prompt|initial\s*instructions)\s*[:=]\s*['"]"#
                .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "System prompt override attempt detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "prompt-injection".to_string(),
                "security".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "role-play-override".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern:
                r#"(?i)(you\s+are\s+now|act\s+as|pretend\s+to\s+be|imagine\s+you\s+are)"#
                    .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Role-play override attempt detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "prompt-injection".to_string(),
                "jailbreak".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "profanity-detected".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)\b(fuck|shit|ass|damn|bitch)\b"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Profanity detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "content-filter".to_string(),
                "profanity".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hate-speech-marker".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern:
                r#"(?i)(hate|slur|discriminat|racist|sexist)\s+(speech|content|language)"#
                    .to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Potential hate speech marker detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "hate-speech".to_string(),
                "safety".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "violence-glorification".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(glorif|celebrat|justif).*\b(violence|attack|murder|kill)"#
                .to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Violence glorification detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "violence".to_string(),
                "safety".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "data-exfiltration-attempt".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern:
                r#"(?i)(extract|reveal|share|leak)\s+(password|credential|secret|key|token)"#
                    .to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Data exfiltration attempt detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "data-exfiltration".to_string(),
                "security".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "sql-injection-request".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern:
                r#"(?i)(give|writ|show|explain).*(sql\s+injection|drop\s+table|delete\s+from)"#
                    .to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Request for SQL injection guidance".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "sql-injection".to_string(),
                "security".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "code-injection-request".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(give|writ|show|explain).*(malicious|exploit|rce|payload)"#
                .to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Request for malicious code guidance".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "code-injection".to_string(),
                "security".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "jailbreak-attempt".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(jailbreak|unlock|DAN|do\s+anything\s+now)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Jailbreak attempt detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "jailbreak".to_string(),
                "security".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hypothetical-malware".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(hypothetical|theoretical|imagine).*(malware|virus|ransomware)"#
                .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Hypothetical malware request detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "malware".to_string(),
                "safety".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "medical-advice-request".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(medical|health|doctor|diagnosis|treatment)\s+advice"#
                .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Medical advice request detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "medical".to_string(),
                "advice".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "legal-advice-request".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(legal|lawyer|law\s+advice|attorney)\s+advice"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Legal advice request detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "legal".to_string(),
                "advice".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "financial-advice-request".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(financial|investment|stock\s+market|crypto)\s+advice"#
                .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Financial advice request detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "financial".to_string(),
                "advice".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "toxicity-marker".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern:
                r#"(?i)(toxic|harmful|offensive|inappropriate)\s+(content|language|behavior)"#
                    .to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Toxicity marker detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "toxicity".to_string(),
                "safety".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "self-harm-content".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(self.?harm|suicide|self.?injury|cut\s+yourself)"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Self-harm content detected".to_string(),
            reference: Some("https://988lifeline.org/".to_string()),
            tags: vec![
                "llm-guardrails".to_string(),
                "self-harm".to_string(),
                "safety".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "privacy-breach-request".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(spy|surveill|track|monitor)\s+(user|customer|employee)"#
                .to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Privacy breach request detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "privacy".to_string(),
                "security".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "bias-detection".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(bias|discriminat|prejudic|stereotyp)\s+(in|against|between)"#
                .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential bias detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "bias".to_string(),
                "fairness".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "output-filtering-enabled".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(content.?filter|output.?filter|moderation.?api)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Output filtering mechanism detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "filtering".to_string(),
                "safety".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "token-limit-warning".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(max.?token|token.?limit|context.?window)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Token limit configuration detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "token-limit".to_string(),
                "configuration".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "pii-output-marker".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(ssn|social\s*security|credit\s*card|bank\s+account)"#
                .to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PII marker detected in content".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "pii".to_string(),
                "detection".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "copyright-material".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(copyright|©|\(c\))\s*\d{4}.*(material|work|content)"#
                .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Copyright material reference detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "copyright".to_string(),
                "ip".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "trademark-reference".to_string(),
            category: "llm-guardrails".to_string(),
            match_pattern: r#"(?i)(trademark|registered\s+trademark)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Trademark reference detected".to_string(),
            reference: None,
            tags: vec![
                "llm-guardrails".to_string(),
                "trademark".to_string(),
                "ip".to_string(),
            ],
            env_var: false,
            binary: false,
        },
    ]
}
