//! Performance patterns - code smells that affect performance

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "sync-in-async".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)(await\s+.*\.)?(sync|sleep|delay|wait)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Synchronous call in async context".to_string(),
            reference: Some("https://rust-lang.github.io/async-book/".to_string()),
            tags: vec![
                "performance".to_string(),
                "async".to_string(),
                "blocking".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "n-plus-one-query".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)for\s*\([^)]*\)\s*\{[^}]*query|for\s*\([^)]*\)\s*\{[^}]*db\. "#
                .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "Potential N+1 query pattern".to_string(),
            reference: Some(
                "https://stackoverflow.com/questions/97197/what-is-the-n1-selects-problem"
                    .to_string(),
            ),
            tags: vec![
                "performance".to_string(),
                "database".to_string(),
                "n+1".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "vector-initial-capacity".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"Vec::new\(\)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Vec::new() without capacity hint - consider Vec::with_capacity()"
                .to_string(),
            reference: Some(
                "https://doc.rust-lang.org/std/vec/struct.Vec.html#method-with_capacity"
                    .to_string(),
            ),
            tags: vec![
                "performance".to_string(),
                "rust".to_string(),
                "memory".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "string-concatenation-loop".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)for\s*\{[^}]*\+\s*="[^\"]*"\}"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "String concatenation in loop - use StringBuilder or join()".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "string".to_string(),
                "memory".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "box-inside-loop".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)for\s*\{[^}]*Box::new"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Box allocation inside loop - consider alternatives".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "memory".to_string(),
                "allocation".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-database-index".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)CREATE\s+TABLE"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "CREATE TABLE without explicit index".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "database".to_string(),
                "index".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "select-star".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)SELECT\s+\*"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "SELECT * detected - consider selecting specific columns".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "database".to_string(),
                "sql".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-limit".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)LIMIT\s+"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Query missing LIMIT clause".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "database".to_string(),
                "sql".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "no-cache-headers".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)Cache-Control|CacheDirectives"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Cache headers not detected in response".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "caching".to_string(),
                "http".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "unsized-image".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"<img[^>]*>"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Image without explicit dimensions".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "image".to_string(),
                "html".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "document-write".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"document\.write"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "document.write() detected - blocks page parsing".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "javascript".to_string(),
                "blocking".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "synchronous-xmlhttprequest".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"new\s+XMLHttpRequest\(\).*send\(null\)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Synchronous XMLHttpRequest blocks UI thread".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "javascript".to_string(),
                "network".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "inner-html-assignment".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)innerHTML\s*="#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "innerHTML assignment may cause performance issues".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "javascript".to_string(),
                "dom".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "force-reflow".to_string(),
            category: "performance".to_string(),
            match_pattern:
                r#"(?i)(offsetHeight|offsetWidth|scrollTop|scrollLeft|clientTop|clientLeft)\s*="#
                    .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Reading layout properties causes forced reflow".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "javascript".to_string(),
                "layout".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "multiple-redirects".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)redirect|301|302|303|307|308"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "HTTP redirect detected".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "http".to_string(),
                "redirect".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gzip-not-enabled".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)Accept-Encoding"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "gzip compression not enabled".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "compression".to_string(),
                "network".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "expensive-computation-loop".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)for\s*\(.*\)\s*\{[^}]*(Math\.|pow\(|sqrt\(|cos\(|sin\()"#
                .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Expensive computation inside loop".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "cpu".to_string(),
                "loop".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "regex-in-loop".to_string(),
            category: "performance".to_string(),
            match_pattern:
                r#"(?i)for\s*\{[^}]*new\s+RegExp|for\s*\{[^}]*\.\.match\(|for\s*\{[^}]*\.\.test\("#
                    .to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Regex creation inside loop - compile outside".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "regex".to_string(),
                "loop".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "no-connection-pool".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)db\.connect|new\s+Connection\(.*\)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Database connection without pooling".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "database".to_string(),
                "pooling".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "event-listener-leak".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)addEventListener"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Event listener added without removeEventListener".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "javascript".to_string(),
                "memory-leak".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "global-variable".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)^var\s+\w+\s*=|window\.\w+\s*="#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Global variable assignment detected".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "javascript".to_string(),
                "memory".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "console-log-production".to_string(),
            category: "performance".to_string(),
            match_pattern: r#"(?i)console\.(log|debug|info).*\/|\s*\(.*\).*eslint"#
                .to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Console logging in production code".to_string(),
            reference: None,
            tags: vec![
                "performance".to_string(),
                "javascript".to_string(),
                "logging".to_string(),
            ],
            env_var: false,
            binary: false,
        },
    ]
}
