//! PII patterns - Personal Identifiable Information detection

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        // US Government IDs
        Pattern {
            name: "ssn".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b\d{3}-\d{2}-\d{4}\b".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Social Security Number (SSN) detected".to_string(),
            reference: Some("https://www.ssa.gov/history/ssn.html".to_string()),
            tags: vec!["pii".to_string(), "ssn".to_string(), "personal".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "ssn-no-dashes".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b\d{3}\d{2}\d{4}\b".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Possible SSN without dashes detected".to_string(),
            reference: Some("https://www.ssa.gov/history/ssn.html".to_string()),
            tags: vec!["pii".to_string(), "ssn".to_string(), "personal".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "itin".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b9\d{2}-\d{2}-\d{4}\b".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Individual Taxpayer Identification Number (ITIN) detected".to_string(),
            reference: Some("https://www.irs.gov/individuals/itin".to_string()),
            tags: vec!["pii".to_string(), "itin".to_string(), "tax".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "ein".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b\d{2}-\d{7}\b".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Employer Identification Number (EIN) detected".to_string(),
            reference: Some("https://www.irs.gov/employers/taxpayer-identification-numbers".to_string()),
            tags: vec!["pii".to_string(), "ein".to_string(), "business".to_string()],
            env_var: false,
            binary: false,
        },
        // Contact information
        Pattern {
            name: "email-address".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Email address detected".to_string(),
            reference: Some("https://tools.ietf.org/html/rfc5322".to_string()),
            tags: vec!["pii".to_string(), "email".to_string(), "personal".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "phone-number".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b(\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Phone number detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "phone".to_string(), "personal".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "international-phone".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"\+?\d{1,3}[-.\s]?\(?\d{1,4}\)?[-.\s]?\d{1,4}[-.\s]?\d{1,9}"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "International phone number detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "phone".to_string(), "international".to_string()],
            env_var: false,
            binary: false,
        },
        // Financial data
        Pattern {
            name: "credit-card-visa".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b4\d{3}[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{4}\b".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Visa credit card number detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/Payment_card_number".to_string()),
            tags: vec!["pii".to_string(), "payment".to_string(), "financial".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "credit-card-mastercard".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b5[1-5]\d{2}[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{4}\b".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Mastercard credit card number detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/Payment_card_number".to_string()),
            tags: vec!["pii".to_string(), "payment".to_string(), "financial".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "credit-card-amex".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b3[47]\d{2}[-\s]?\d{6}[-\s]?\d{5}\b".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "American Express credit card number detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/Payment_card_number".to_string()),
            tags: vec!["pii".to_string(), "payment".to_string(), "financial".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "credit-card-discover".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b6(?:011|5[0-9]{2})[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{4}\b".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Discover credit card number detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/Payment_card_number".to_string()),
            tags: vec!["pii".to_string(), "payment".to_string(), "financial".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "credit-card-number-generic".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12})\b".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Generic credit card number detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/Payment_card_number".to_string()),
            tags: vec!["pii".to_string(), "payment".to_string(), "financial".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "cvv".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)\b(?:cvv|cvc|security\s*code)\s*[:=]\s*\d{3,4}\b"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Card verification value (CVV/CVC) detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/Card_security_code".to_string()),
            tags: vec!["pii".to_string(), "payment".to_string(), "cvv".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "bank-routing-number".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b\d{9}\b".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Bank routing number (ABA) detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/ABA_routing_transit_number".to_string()),
            tags: vec!["pii".to_string(), "banking".to_string(), "financial".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "iban".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b[A-Z]{2}\d{2}[A-Z0-9]{11,30}\b".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "International Bank Account Number (IBAN) detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/International_Bank_Account_Number".to_string()),
            tags: vec!["pii".to_string(), "banking".to_string(), "international".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "bitcoin-address".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"\b[13][a-km-zA-HJ-NP-Z1-9]{25,34}\b"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Bitcoin address detected".to_string(),
            reference: Some("https://en.wikipedia.org/wiki/Bitcoin".to_string()),
            tags: vec!["pii".to_string(), "cryptocurrency".to_string(), "financial".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "aws-access-key".to_string(),
            category: "pii".to_string(),
            match_pattern: r"AKIA[0-9A-Z]{16}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "AWS Access Key ID detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html".to_string()),
            tags: vec!["pii".to_string(), "aws".to_string(), "credential".to_string()],
            env_var: false,
            binary: false,
        },
        // Names and identifiers
        Pattern {
            name: "full-name".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)\b(first\s+name|last\s+name|full\s+name|surname|given\s+name)\s*[:=]\s*['\"][A-Za-z\s]+['\"]"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Full name field detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "name".to_string(), "personal".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "date-of-birth".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(dob|date\s*of\s*birth|birth\s*date|birthday)\s*[:=]\s*['\"]?\d{1,2}[/-]\d{1,2}[/-]\d{2,4}"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Date of birth field detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "dob".to_string(), "personal".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "passport-number".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(passport|passport\s*#|passport\s*number)\s*[:=]\s*['\"]?[A-Z0-9]{6,9}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Passport number detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "passport".to_string(), "travel".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "drivers-license".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(drivers?\s*license|dl\s*#|license\s*#)\s*[:=]\s*['\"]?[A-Z0-9]{5,20}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Driver's license number detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "license".to_string(), "personal".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "national-id".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(national\s*id|identity\s*card|id\s*number)\s*[:=]\s*['\"]?[A-Z0-9]{5,20}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "National ID number detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "national-id".to_string(), "personal".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "military-id".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(military\s*id|service\s*number|us\s*military)\s*[:=]\s*['\"]?[A-Z0-9]{6,10}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Military ID detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "military".to_string(), "government".to_string()],
            env_var: false,
            binary: false,
        },
        // Address patterns
        Pattern {
            name: "street-address".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(address|street|street\s*address)\s*[:=]\s*['\"]?\d+\s+[A-Za-z\s]+"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Street address detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "address".to_string(), "location".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "zip-code".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b\d{5}(?:[-\s]\d{4})?\b".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "US ZIP code detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "zip".to_string(), "location".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "uk-national-insurance".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b[A-Z]{2}\d{6}[A-Z]\b".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "UK National Insurance number detected".to_string(),
            reference: Some("https://www.gov.uk/national-insurance".to_string()),
            tags: vec!["pii".to_string(), "uk".to_string(), "government".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "canadian-sin".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b\d{3}-\d{3}-\d{3}\b".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Canadian Social Insurance Number (SIN) detected".to_string(),
            reference: Some("https://www.canada.ca/en/employment-social-development/services/sin.html".to_string()),
            tags: vec!["pii".to_string(), "canada".to_string(), "sin".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "australian-tfn".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b\d{3}[-\s]?\d{3}[-\s]?\d{3}\b".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Australian Tax File Number (TFN) detected".to_string(),
            reference: Some("https://www.ato.gov.au/individual/tax-file-number".to_string()),
            tags: vec!["pii".to_string(), "australia".to_string(), "tax".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "indian-aadhaar".to_string(),
            category: "pii".to_string(),
            match_pattern: r"\b\d{4}[-\s]?\d{4}[-\s]?\d{4}\b".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Indian Aadhaar number detected".to_string(),
            reference: Some("https://uidai.gov.in/".to_string()),
            tags: vec!["pii".to_string(), "india".to_string(), "aadhaar".to_string()],
            env_var: false,
            binary: false,
        },
        // Medical and Health
        Pattern {
            name: "medical-record-number".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(mrn|medical\s*record|patient\s*id)\s*[:=]\s*['\"]?\d{5,10}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Medical Record Number (MRN) detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "medical".to_string(), "health".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "health-insurance-number".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(health\s*insurance|insurance\s*id|member\s*id)\s*[:=]\s*['\"]?[A-Z0-9]{6,15}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Health insurance number detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "insurance".to_string(), "health".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "prescription-number".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(prescription|rx\s*#)\s*[:=]\s*['\"]?\d{5,10}"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Prescription number detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "medical".to_string(), "prescription".to_string()],
            env_var: false,
            binary: false,
        },
        // Authentication credentials
        Pattern {
            name: "username-field".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(username|user\s*name|login)\s*[:=]\s*['\"][^'\"]{3,}"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Username field with value detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "username".to_string(), "auth".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "password-field".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(password|passwd|pwd|secret)\s*[:=]\s*['\"][^'\"]{3,}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Password field with value detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "password".to_string(), "credential".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "api-key-field".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(api\s*key|apikey|api\s*token)\s*[:=]\s*['\"][^'\"]{10,}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "API key field with value detected".to_string(),
            reference: None,
            tags: vec!["pii".to_string(), "api-key".to_string(), "credential".to_string()],
            env_var: false,
            binary: false,
        },
        // GDPR/Privacy keywords
        Pattern {
            name: "gdpr-personal-data".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)personal\s*data"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Reference to personal data detected".to_string(),
            reference: Some("https://gdpr.eu/article-4-definitions/".to_string()),
            tags: vec!["pii".to_string(), "gdpr".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "data-processing".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)data\s*processing\s*agreement"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Data processing agreement reference detected".to_string(),
            reference: Some("https://gdpr.eu/article-28-processors/".to_string()),
            tags: vec!["pii".to_string(), "gdpr".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "consent-record".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)consent\s*(record|management|given)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "User consent record detected".to_string(),
            reference: Some("https://gdpr.eu/article-7-conditions-for-consent/".to_string()),
            tags: vec!["pii".to_string(), "consent".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "right-to-erasure".to_string(),
            category: "pii".to_string(),
            match_pattern: r#"(?i)(right\s*to\s*erasure|right\s*to\s*be\s*forgotten|delete\s*request)"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Right to erasure request detected".to_string(),
            reference: Some("https://gdpr.eu/article-17-right-to-erasure/".to_string()),
            tags: vec!["pii".to_string(), "gdpr".to_string(), "privacy".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
