//! PWA patterns

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "caching-strategy".to_string(),
            category: "pwa".to_string(),
            match_pattern: r#"cache.*first.*network|network.*first.*cache|stale.*while.*revalidate"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PWA caching strategy issue".to_string(),
            reference: None,
            tags: vec!["pwa".to_string(), "caching".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "manifest".to_string(),
            category: "pwa".to_string(),
            match_pattern: r#"manifest.*name.*short_name.*different|display.*standalone.*theme_color.*different|icons.*192.*512"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PWA manifest configuration issue".to_string(),
            reference: None,
            tags: vec!["pwa".to_string(), "manifest".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "offline-support".to_string(),
            category: "pwa".to_string(),
            match_pattern: r#"offline.*html.*503|navigator\.onLine.*false|fallback.*page.*offline"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PWA offline support issue".to_string(),
            reference: None,
            tags: vec!["pwa".to_string(), "offline".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "service-worker".to_string(),
            category: "pwa".to_string(),
            match_pattern: r#"cache.*addAll.*urls.*100\+|fetch.*respondWith.*cache.*match.*network|skipWaiting\(\).*clients\.claim"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PWA service worker issue".to_string(),
            reference: None,
            tags: vec!["pwa".to_string(), "service-worker".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "shortcuts".to_string(),
            category: "pwa".to_string(),
            match_pattern: r#"shortcuts.*name.*url|icons.*shortcuts.*manifest|app.*shortcuts.*home.*screen"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PWA shortcuts configuration issue".to_string(),
            reference: None,
            tags: vec!["pwa".to_string(), "shortcuts".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
