//! Secret patterns - API keys, tokens, credentials

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "secrets-aws-access-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"AKIA[0-9A-Z]{16}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "AWS Access Key ID detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html".to_string()),
            tags: vec!["aws".to_string(), "cloud".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "secrets-aws-secret-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r#"(?i)aws(.{0,20})?['"][0-9a-zA-Z/+]{40}['"]"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "AWS Secret Access Key detected".to_string(),
            reference: Some("https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html".to_string()),
            tags: vec!["aws".to_string(), "cloud".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "secrets-github-token".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"gh[pousr]_[A-Za-z0-9_]{36,}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "GitHub Token detected".to_string(),
            reference: Some("https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-tokens".to_string()),
            tags: vec!["github".to_string(), "token".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "gitlab-token".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"glpat-[A-Za-z0-9\-_]{20}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "GitLab Personal Access Token detected".to_string(),
            reference: Some("https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html".to_string()),
            tags: vec!["gitlab".to_string(), "token".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "secrets-slack-token".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"xox[baprs]-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "Slack Token detected".to_string(),
            reference: Some("https://api.slack.com/authentication/token-types".to_string()),
            tags: vec!["slack".to_string(), "token".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "secrets-stripe-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"sk_live_[0-9a-zA-Z]{24}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Stripe API Key detected".to_string(),
            reference: Some("https://stripe.com/docs/keys".to_string()),
            tags: vec!["stripe".to_string(), "payment".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "secrets-stripe-publishable-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"pk_live_[0-9a-zA-Z]{24}".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Stripe Publishable Key detected".to_string(),
            reference: Some("https://stripe.com/docs/keys".to_string()),
            tags: vec!["stripe".to_string(), "payment".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "secrets-sendgrid-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"SG\.[0-9a-zA-Z_-]{22}\.[0-9a-zA-Z_-]{43}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "SendGrid API Key detected".to_string(),
            reference: Some("https://docs.sendgrid.com/api-reference/api-key-permissions".to_string()),
            tags: vec!["sendgrid".to_string(), "email".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "secrets-twilio-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"SK[0-9a-fA-F]{32}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Twilio API Key detected".to_string(),
            reference: Some("https://www.twilio.com/docs/iam/keys".to_string()),
            tags: vec!["twilio".to_string(), "sms".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "ssh-private-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"-----BEGIN (?:RSA |DSA |EC |OPENSSH |PGP )?PRIVATE KEY-----".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "SSH Private Key detected".to_string(),
            reference: Some("https://man.openbsd.org/ssh-keygen.1".to_string()),
            tags: vec!["ssh".to_string(), "private-key".to_string(), "credential".to_string()],
            env_var: false,
            binary: true,
        },
        Pattern {
            name: "pgp-private-key".to_string(),
            category: "secrets".to_string(),
            // This detector literal is intentionally not a credential.
            match_pattern: r"-----BEGIN PGP PRIVATE KEY BLOCK-----".to_string(), // aegis:ignore:pgp-private-key,ssh-private-key
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PGP Private Key detected".to_string(),
            reference: Some("https://gnupg.org/documentation/manuals/gnupg/GPG-Key-generation.html".to_string()),
            tags: vec!["pgp".to_string(), "gpg".to_string(), "private-key".to_string()],
            env_var: false,
            binary: true,
        },
        Pattern {
            name: "jwt-token".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"eyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: Some(4.0),
            description: "JWT Token detected".to_string(),
            reference: Some("https://datatracker.ietf.org/doc/html/rfc7519".to_string()),
            tags: vec!["jwt".to_string(), "token".to_string(), "auth".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "google-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"AIza[0-9A-Za-z_-]{35}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Google API Key detected".to_string(),
            reference: Some("https://cloud.google.com/docs/authentication/api-keys".to_string()),
            tags: vec!["google".to_string(), "cloud".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "google-oauth-token".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"ya29\.[0-9A-Za-z_-]+".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "Google OAuth Token detected".to_string(),
            reference: Some("https://developers.google.com/identity/protocols/oauth2".to_string()),
            tags: vec!["google".to_string(), "oauth".to_string(), "token".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "azure-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"[a-zA-Z0-9+/]{32,}$".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "low".to_string(),
            min_entropy: Some(4.5),
            description: "Potential Azure API Key detected".to_string(),
            reference: Some("https://docs.microsoft.com/en-us/azure/api-management/api-management-subscriptions".to_string()),
            tags: vec!["azure".to_string(), "cloud".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "mailchimp-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"[a-f0-9]{32}-us[0-9]{1,2}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "Mailchimp API Key detected".to_string(),
            reference: Some("https://mailchimp.com/help/about-api-keys/".to_string()),
            tags: vec!["mailchimp".to_string(), "email".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "twitter-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"[A-Za-z0-9]{25,}".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: Some(4.0),
            description: "Twitter API Key detected".to_string(),
            reference: Some("https://developer.twitter.com/en/docs/authentication/oauth-1-0a".to_string()),
            tags: vec!["twitter".to_string(), "api".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "discord-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"[A-Za-z\d]{24}\.[\w-]{6}\.[\w-]{27}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Discord API Key detected".to_string(),
            reference: Some("https://discord.com/developers/docs/reference".to_string()),
            tags: vec!["discord".to_string(), "api".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "dropbox-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"[a-zA-Z0-9]{40,}".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: Some(4.5),
            description: "Dropbox API Key detected".to_string(),
            reference: Some("https://www.dropbox.com/developers/reference".to_string()),
            tags: vec!["dropbox".to_string(), "api".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "heroku-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"[h|H][e|E][r|R][o|O][k|K][u|U][0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "Heroku API Key detected".to_string(),
            reference: Some("https://devcenter.heroku.com/articles/authentication".to_string()),
            tags: vec!["heroku".to_string(), "cloud".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "npm-token".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"npm_[A-Za-z0-9]{36}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "NPM Access Token detected".to_string(),
            reference: Some("https://docs.npmjs.com/about-access-tokens".to_string()),
            tags: vec!["npm".to_string(), "registry".to_string(), "token".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "private-key-encrypted".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"-----BEGIN (?:RSA |DSA |EC )?ENCRYPTED PRIVATE KEY-----".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Encrypted Private Key detected".to_string(),
            reference: Some("https://man.openbsd.org/ssh-keygen.1".to_string()),
            tags: vec!["ssh".to_string(), "private-key".to_string(), "encrypted".to_string()],
            env_var: false,
            binary: true,
        },
        Pattern {
            name: "hardcoded-password".to_string(),
            category: "secrets".to_string(),
            match_pattern: r#"(?i)(password|passwd|pwd|secret)\s*[:=]\s*['"][^'"]{3,}['"]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: Some(2.5),
            description: "Hardcoded password detected".to_string(),
            reference: Some("https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure".to_string()),
            tags: vec!["password".to_string(), "hardcoded".to_string(), "credential".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hardcoded-username".to_string(),
            category: "secrets".to_string(),
            match_pattern: r#"(?i)(username|user|login)\s*[:=]\s*['"][^'"]{2,}['"]"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "low".to_string(),
            min_entropy: Some(2.0),
            description: "Hardcoded username detected".to_string(),
            reference: Some("https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure".to_string()),
            tags: vec!["username".to_string(), "hardcoded".to_string(), "credential".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "database-connection-string".to_string(),
            category: "secrets".to_string(),
            match_pattern: r#"(?i)(mongodb|postgres|mysql|redis|mssql)://[^\s'"]{10,}"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(3.5),
            description: "Database connection string detected".to_string(),
            reference: Some("https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure".to_string()),
            tags: vec!["database".to_string(), "connection-string".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "connection-string-with-password".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"(?i)(server|host|data source).*(password|pwd).*[;=]".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "medium".to_string(),
            min_entropy: Some(3.0),
            description: "Connection string with password detected".to_string(),
            reference: Some("https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure".to_string()),
            tags: vec!["connection-string".to_string(), "password".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "api-key-in-url".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"(?i)[?&](api_key|api-key|apikey|access_token|auth_token)=[a-zA-Z0-9_-]{10,}".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(3.5),
            description: "API Key embedded in URL detected".to_string(),
            reference: Some("https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure".to_string()),
            tags: vec!["api-key".to_string(), "url".to_string(), "credential".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "bearer-token".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"(?i)bearer\s+[a-zA-Z0-9_=-]{10,}".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "Bearer Token detected".to_string(),
            reference: Some("https://datatracker.ietf.org/doc/html/rfc6750".to_string()),
            tags: vec!["bearer".to_string(), "token".to_string(), "auth".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "basic-auth-credentials".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"(?i)basic\s+[a-zA-Z0-9+/=]{10,}".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "Basic Authentication credentials detected".to_string(),
            reference: Some("https://datatracker.ietf.org/doc/html/rfc7617".to_string()),
            tags: vec!["basic-auth".to_string(), "credential".to_string(), "auth".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "facebook-access-token".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"EAACEdEose0cBA[0-9A-Za-z]+".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Facebook Access Token detected".to_string(),
            reference: Some("https://developers.facebook.com/docs/facebook-login/guides/access-tokens".to_string()),
            tags: vec!["facebook".to_string(), "token".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "firebase-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"AIza[0-9A-Za-z_-]{35}".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Firebase API Key detected".to_string(),
            reference: Some("https://firebase.google.com/docs/api-keys".to_string()),
            tags: vec!["firebase".to_string(), "google".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "openai-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"sk-[A-Za-z0-9]{48}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "OpenAI API Key detected".to_string(),
            reference: Some("https://platform.openai.com/docs/api-keys".to_string()),
            tags: vec!["openai".to_string(), "ai".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "anthropic-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"sk-ant-[A-Za-z0-9_-]{48,}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "Anthropic API Key detected".to_string(),
            reference: Some("https://docs.anthropic.com/en/api".to_string()),
            tags: vec!["anthropic".to_string(), "ai".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "huggingface-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"hf_[A-Za-z0-9]{34,}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "HuggingFace API Key detected".to_string(),
            reference: Some("https://huggingface.co/docs/api-keys".to_string()),
            tags: vec!["huggingface".to_string(), "ai".to_string(), "api-key".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "rsa-private-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"-----BEGIN RSA PRIVATE KEY-----".to_string(), // aegis:ignore:rsa-private-key,ssh-private-key
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "RSA Private Key detected".to_string(),
            reference: Some("https://man.openbsd.org/ssh-keygen.1".to_string()),
            tags: vec!["rsa".to_string(), "private-key".to_string(), "credential".to_string()],
            env_var: false,
            binary: true,
        },
        Pattern {
            name: "ec-private-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"-----BEGIN EC PRIVATE KEY-----".to_string(), // aegis:ignore:ec-private-key,ssh-private-key
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "EC Private Key detected".to_string(),
            reference: Some("https://man.openbsd.org/ssh-keygen.1".to_string()),
            tags: vec!["ec".to_string(), "private-key".to_string(), "credential".to_string()],
            env_var: false,
            binary: true,
        },
        Pattern {
            name: "github-ssh-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"-----BEGIN OPENSSH PRIVATE KEY-----".to_string(), // aegis:ignore:github-ssh-key,ssh-private-key
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "OpenSSH Private Key detected (possibly GitHub)".to_string(),
            reference: Some("https://man.openbsd.org/ssh-keygen.1".to_string()),
            tags: vec!["ssh".to_string(), "private-key".to_string(), "github".to_string()],
            env_var: false,
            binary: true,
        },
        Pattern {
            name: "generic-api-key".to_string(),
            category: "secrets".to_string(),
            match_pattern: r#"(?i)(api[_-]?key|apikey|api_secret|secret[_-]?key)\s*[:=]\s*['"][A-Za-z0-9]{16,}['"]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: Some(4.0),
            description: "Generic API Key detected".to_string(),
            reference: None,
            tags: vec!["api-key".to_string(), "generic".to_string(), "credential".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "generic-secret".to_string(),
            category: "secrets".to_string(),
            match_pattern: r#"(?i)(secret|token|auth)[_-]?(token|key|secret)?\s*[:=]\s*['"][A-Za-z0-9]{16,}['"]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: Some(4.0),
            description: "Generic secret/token detected".to_string(),
            reference: None,
            tags: vec!["secret".to_string(), "token".to_string(), "generic".to_string()],
            env_var: true,
            binary: false,
        },
        Pattern {
            name: "github-oauth-token".to_string(),
            category: "secrets".to_string(),
            match_pattern: r"gho_[A-Za-z0-9]{36}".to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.5),
            description: "GitHub OAuth Token detected".to_string(),
            reference: Some("https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-tokens".to_string()),
            tags: vec!["github".to_string(), "oauth".to_string(), "token".to_string()],
            env_var: true,
            binary: false,
        },
    ]
}
