//! Security hardening patterns - security best practices and vulnerability detection

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "weak-ssl".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(ssl_v2|ssl_v3|tls_1[01]|md5|sha1)\s*[=:]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Weak cryptographic protocol/algorithm detected".to_string(),
            reference: Some("https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure".to_string()),
            tags: vec!["crypto".to_string(), "security".to_string(), "ssl".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hardcoded-encryption-key".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(encryption_key|encrypt_key|crypto_key)\s*[:=]\s*['"][^'"]{8,}"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(3.5),
            description: "Hardcoded encryption key detected".to_string(),
            reference: None,
            tags: vec!["crypto".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "insecure-random".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)Math\.random\(\)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Insecure random number generation (Math.random)".to_string(),
            reference: None,
            tags: vec!["security".to_string(), "random".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "sql-query".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)SELECT|INSERT|UPDATE|DELETE|DROP|ALTER"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "SQL query detected (potential SQL injection)".to_string(),
            reference: None,
            tags: vec!["sql".to_string(), "database".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "security-hardening-command-injection".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(exec|system|popen|shell_exec)\s*\(\s*["'].*\$\{?[\w_]"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential command injection vulnerability".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/Command_Injection".to_string()),
            tags: vec!["injection".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "security-hardening-path-traversal".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)\.\.[\\/]|\.\.%2f|%2e%2e"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Potential path traversal vulnerability".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/Path_Traversal".to_string()),
            tags: vec!["injection".to_string(), "security".to_string(), "path".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "xss-vulnerability".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(innerHTML|outerHTML|document\.write)\s*\([^)]*\+"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential XSS vulnerability (unsafe DOM manipulation)".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/xss/".to_string()),
            tags: vec!["xss".to_string(), "security".to_string(), "javascript".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "insecure-cookie".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)cookie.*(secure|samesite).*=.*false"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Insecure cookie configuration detected".to_string(),
            reference: None,
            tags: vec!["cookie".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "csrf-missing".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)csrf|srftoken|csrf_token"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "CSRF protection reference detected".to_string(),
            reference: None,
            tags: vec!["csrf".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hardcoded-iv".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(iv|initialization_vector)\s*[:=]\s*['"][a-fA-F0-9]{16,}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(3.5),
            description: "Hardcoded IV detected for encryption".to_string(),
            reference: None,
            tags: vec!["crypto".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "jwt-secret-hardcoded".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(jwt|json.web.token)\s*[:=]\s*['"][^'\"]{16,}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(4.0),
            description: "Hardcoded JWT secret detected".to_string(),
            reference: None,
            tags: vec!["jwt".to_string(), "security".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "private-key-exposed".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(PRIVATE\s+KEY|-----\s*BEGIN\s+.*PRIVATE\s+KEY-----)"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(5.0),
            description: "Private key exposed in code".to_string(),
            reference: None,
            tags: vec!["crypto".to_string(), "security".to_string(), "keys".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "password-in-url".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)https?://[^:]+:[^@]+@"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Password embedded in URL detected".to_string(),
            reference: None,
            tags: vec!["security".to_string(), "credentials".to_string(), "url".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "bearer-token-url".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)bearer\s+[A-Za-z0-9_\-\.]+"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Bearer token detected in code".to_string(),
            reference: None,
            tags: vec!["security".to_string(), "auth".to_string(), "token".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "basic-auth-url".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)https?://[^:]+:[^@/]+@"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Basic authentication credentials in URL".to_string(),
            reference: None,
            tags: vec!["security".to_string(), "auth".to_string(), "credentials".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "security-hardening-aws-access-key".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(AKIA|ABIA|ACCA|ASIA)[A-Z0-9]{16}"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(5.0),
            description: "AWS access key ID detected".to_string(),
            reference: None,
            tags: vec!["aws".to_string(), "security".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "aws-secret-key".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)aws_secret(access_key|key)\s*[:=]\s*['\"][A-Za-z0-9/+=]{40}"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(5.0),
            description: "AWS secret access key detected".to_string(),
            reference: None,
            tags: vec!["aws".to_string(), "security".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "github-token".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{36,}"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(5.0),
            description: "GitHub token detected".to_string(),
            reference: None,
            tags: vec!["github".to_string(), "security".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "slack-token".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)xox[baprs]-[0-9]{10,12}-[0-9]{10,12}-[A-Za-z0-9]+"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(5.0),
            description: "Slack token detected".to_string(),
            reference: None,
            tags: vec!["slack".to_string(), "security".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "stripe-api-key".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(sk|pk)_(?:live|test)_[A-Za-z0-9]{24,}"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(5.0),
            description: "Stripe API key detected".to_string(),
            reference: None,
            tags: vec!["stripe".to_string(), "security".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "sendgrid-api-key".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(5.0),
            description: "SendGrid API key detected".to_string(),
            reference: None,
            tags: vec!["sendgrid".to_string(), "security".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "twilio-api-key".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)SK[a-zA-Z0-9]{32}"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(5.0),
            description: "Twilio API key detected".to_string(),
            reference: None,
            tags: vec!["twilio".to_string(), "security".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "mailgun-api-key".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(key|api)[_-]?(key)?\s*[:=]\s*['\"][a-zA-Z0-9]{32}"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "medium".to_string(),
            min_entropy: Some(4.5),
            description: "Mailgun API key detected".to_string(),
            reference: None,
            tags: vec!["mailgun".to_string(), "security".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "security-hardening-jwt-none-algorithm".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(alg.*none|algorithm.*none|none.*algorithm)"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "JWT 'none' algorithm vulnerability detected".to_string(),
            reference: Some("https://owasp.org/www-project-web-security-testing/latest/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens".to_string()),
            tags: vec!["jwt".to_string(), "security".to_string(), "algorithm".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "security-hardening-xml-external-entity".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)<!ENTITY|SYSTEM\s+\"|PUBLIC\s+\""#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "XML External Entity (XXE) vulnerability detected".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/XML_External_Entities_(XXE)_Processing".to_string()),
            tags: vec!["xxe".to_string(), "security".to_string(), "xml".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "deserialization-vulnerability".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(unpickle|unserialize|ObjectInputStream|YAML\.load)\s*\("#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Potential insecure deserialization vulnerability".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/Insecure_Deserialization".to_string()),
            tags: vec!["deserialization".to_string(), "security".to_string(), "rce".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "eval-usage".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)\beval\s*\("#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dangerous eval() usage detected".to_string(),
            reference: None,
            tags: vec!["security".to_string(), "eval".to_string(), "rce".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "setuid-root".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)chmod\s+[47]\d{3}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Setuid/Setgid permissions detected".to_string(),
            reference: None,
            tags: vec!["security".to_string(), "permissions".to_string(), "linux".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "world-writable".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)chmod\s+777|chmod\s+a\+rw"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "World-writable file permissions detected".to_string(),
            reference: None,
            tags: vec!["security".to_string(), "permissions".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "sensitive-file-access".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(/etc/passwd|/etc/shadow|\.ssh|\.aws|\.git/config)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Access to sensitive system files detected".to_string(),
            reference: None,
            tags: vec!["security".to_string(), "filesystem".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "ldap-injection".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(ldap|LDAP).*\+.*request|screen\s*name"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential LDAP injection vulnerability".to_string(),
            reference: None,
            tags: vec!["ldap".to_string(), "injection".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "xpath-injection".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(xpath|XPath).*\+.*input|string concatenation"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential XPath injection vulnerability".to_string(),
            reference: None,
            tags: vec!["xpath".to_string(), "injection".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "ssti-template".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(template|render|view)\s*\.\s*(format|render|make)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential server-side template injection".to_string(),
            reference: None,
            tags: vec!["ssti".to_string(), "injection".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
