//! Security hardening patterns

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "weak-ssl".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(ssl_v2|ssl_v3|tls_1[01]|md5|sha1)\s*[=:]"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Weak cryptographic protocol/algorithm detected".to_string(),
            reference: Some(
                "https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure"
                    .to_string(),
            ),
            tags: vec![
                "crypto".to_string(),
                "security".to_string(),
                "ssl".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hardcoded-encryption-key".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(encryption_key|encrypt_key|crypto_key)\s*[:=]\s*['"][^'"]{8,}"#
                .to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(3.5),
            description: "Hardcoded encryption key detected".to_string(),
            reference: None,
            tags: vec!["crypto".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "insecure-random".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r"(?i)Math\.random\(\)".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Insecure random number generation (Math.random)".to_string(),
            reference: None,
            tags: vec!["security".to_string(), "random".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "sql-query".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r"(?i)SELECT|INSERT|UPDATE|DELETE|DROP|ALTER".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "SQL query detected (potential SQL injection)".to_string(),
            reference: None,
            tags: vec!["sql".to_string(), "database".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "command-injection".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(exec|system|popen|shell_exec)\s*\(\s*["'].*\$\{?[\w_]"#
                .to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential command injection vulnerability".to_string(),
            reference: Some(
                "https://owasp.org/www-community/attacks/Command_Injection".to_string(),
            ),
            tags: vec!["injection".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "path-traversal".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r"(?i)\.\.[\\/]|\.\.%2f|%2e%2e".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Potential path traversal vulnerability".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/Path_Traversal".to_string()),
            tags: vec![
                "injection".to_string(),
                "security".to_string(),
                "path".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "xss-vulnerability".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r"(?i)(innerHTML|outerHTML|document\.write)\s*\([^)]*\+".to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential XSS vulnerability (unsafe DOM manipulation)".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/xss/".to_string()),
            tags: vec![
                "xss".to_string(),
                "security".to_string(),
                "javascript".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "insecure-cookie".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r"(?i)cookie.*(secure|samesite).*=.*false".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Insecure cookie configuration detected".to_string(),
            reference: None,
            tags: vec!["cookie".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "csrf-missing".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r"(?i)csrf|srftoken|csrf_token".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "CSRF protection reference detected".to_string(),
            reference: None,
            tags: vec!["csrf".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hardcoded-iv".to_string(),
            category: "security-hardening".to_string(),
            match_pattern: r#"(?i)(iv|initialization_vector)\s*[:=]\s*['"][a-fA-F0-9]{16,}"#
                .to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: Some(3.5),
            description: "Hardcoded IV detected for encryption".to_string(),
            reference: None,
            tags: vec!["crypto".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
