//! Shift-left patterns - early detection, CI/CD integration, automation

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "precommit-marker".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"(?i)(pre-commit|precommit|commit-msg)".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Pre-commit hook marker detected".to_string(),
            reference: Some("https://pre-commit.com/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "ci-cd".to_string(),
                "hooks".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "pr-review-marker".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"(?i)(pull.request|code.review|review.required)".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "PR review marker detected".to_string(),
            reference: None,
            tags: vec![
                "shift-left".to_string(),
                "pr".to_string(),
                "review".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        // CI/CD patterns
        Pattern {
            name: "shift-left-github-actions-workflow".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"\.github/workflows/[^/]+\.ya?ml".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GitHub Actions workflow detected".to_string(),
            reference: Some("https://docs.github.com/en/actions/learn-github-actions".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "github".to_string(),
                "ci-cd".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gitlab-ci-pipeline".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"\.gitlab-ci\.yml".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GitLab CI pipeline detected".to_string(),
            reference: Some("https://docs.gitlab.com/ee/ci/yaml/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "gitlab".to_string(),
                "ci-cd".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "jenkinsfile".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"Jenkinsfile".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Jenkinsfile detected".to_string(),
            reference: Some("https://www.jenkins.io/doc/book/pipeline/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "jenkins".to_string(),
                "ci-cd".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "azure-pipeline".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"azure-pipelines\.ya?ml".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Azure Pipeline detected".to_string(),
            reference: Some("https://docs.microsoft.com/en-us/azure/devops/pipelines/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "azure".to_string(),
                "ci-cd".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "circleci-config".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"\.circleci/config\.yml".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CircleCI config detected".to_string(),
            reference: Some("https://circleci.com/docs/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "circleci".to_string(),
                "ci-cd".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "travis-yml".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"\.travis\.yml".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Travis CI config detected".to_string(),
            reference: Some("https://docs.travis-ci.com/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "travis".to_string(),
                "ci-cd".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "drone-ci".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"\.drone\.yml".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Drone CI config detected".to_string(),
            reference: Some("https://docs.drone.io/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "drone".to_string(),
                "ci-cd".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        // Quality gates
        Pattern {
            name: "codecov-config".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"codecov\.yml|codeclimate\.yml".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Code coverage config detected".to_string(),
            reference: Some("https://docs.codecov.io/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "coverage".to_string(),
                "quality".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "sonarqube-config".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"sonar-project\.properties|sonar.*\.yml".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "SonarQube config detected".to_string(),
            reference: Some("https://docs.sonarqube.org/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "sonarqube".to_string(),
                "quality".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "snyk-config".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"\.snyk|snyk.*\.yml".to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Snyk security config detected".to_string(),
            reference: Some("https://docs.snyk.io/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "snyk".to_string(),
                "security".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "shift-left-dependabot-config".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"dependabot\.yml".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dependabot config detected".to_string(),
            reference: Some("https://docs.github.com/en/code-security/dependabot".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "dependabot".to_string(),
                "dependencies".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        // Testing patterns
        Pattern {
            name: "unit-test-marker".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"(?i)@Test|@test|def\s+test_|test\s*\(\s*".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Unit test marker detected".to_string(),
            reference: None,
            tags: vec![
                "shift-left".to_string(),
                "testing".to_string(),
                "unit".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "integration-test-marker".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"(?i)integration.*test|@IntegrationTest|e2e|e2e.*test".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Integration test marker detected".to_string(),
            reference: None,
            tags: vec![
                "shift-left".to_string(),
                "testing".to_string(),
                "integration".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "security-test-marker".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"(?i)security.*test|@SecuredTest|pen.*test|vuln.*test".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Security test marker detected".to_string(),
            reference: None,
            tags: vec![
                "shift-left".to_string(),
                "testing".to_string(),
                "security".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        // IaC scanning
        Pattern {
            name: "terraform-validate".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"(?i)terraform\s+validate|terraform\s+plan".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Terraform validate command detected".to_string(),
            reference: Some("https://www.terraform.io/docs/commands/validate.html".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "terraform".to_string(),
                "iac".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "checkov-config".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"(?i)checkov|terragrunt|terraform-compliance".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "IaC security scanning tool detected".to_string(),
            reference: Some("https://www.checkov.io/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "checkov".to_string(),
                "iac".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        // Container scanning
        Pattern {
            name: "trivy-config".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"(?i)trivy|aqua.*security|anchore".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Container vulnerability scanning tool detected".to_string(),
            reference: Some("https://aquasecurity.github.io/trivy/".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "trivy".to_string(),
                "container".to_string(),
            ],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "grype-config".to_string(),
            category: "shift-left".to_string(),
            match_pattern: r"(?i)grype|synthonizer".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Container vulnerability scanning with Grype detected".to_string(),
            reference: Some("https://github.com/anchore/grype".to_string()),
            tags: vec![
                "shift-left".to_string(),
                "grype".to_string(),
                "container".to_string(),
            ],
            env_var: false,
            binary: false,
        },
    ]
}
