//! Supply chain patterns - dependencies, package managers, integrity

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "unknown-npm-package".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r"(?i)npm\s+(install|add)\s+([a-z0-9_-]+@[0-9]+\.[0-9]+\.[0-9]+|[a-z0-9_-]+\.[a-z0-9_-]+)".to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "low".to_string(),
            min_entropy: None,
            description: "NPM package installation detected".to_string(),
            reference: Some("https://docs.npmjs.com/cli/v8/commands/npm-install".to_string()),
            tags: vec!["npm".to_string(), "supply-chain".to_string(), "package".to_string()],
            env_var: false,
            binary: false,
        },
        // Package.json patterns
        Pattern {
            name: "package-json".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"package\.json"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "package.json file detected".to_string(),
            reference: Some("https://docs.npmjs.com/creating-a-package-json-file".to_string()),
            tags: vec!["npm".to_string(), "package".to_string(), "manifest".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "npm-shrinkwrap".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"npm-shrinkwrap\.json"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "NPM shrinkwrap file detected".to_string(),
            reference: Some("https://docs.npmjs.com/cli/v8/commands/npm-shrinkwrap".to_string()),
            tags: vec!["npm".to_string(), "lockfile".to_string(), "reproducible".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "yarn-lockfile".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"yarn\.lock"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Yarn lockfile detected".to_string(),
            reference: Some("https://yarnpkg.com/getting-started/qa".to_string()),
            tags: vec!["yarn".to_string(), "lockfile".to_string(), "reproducible".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "pnpm-lockfile".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"pnpm-lock\.yaml"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "PNPM lockfile detected".to_string(),
            reference: Some("https://pnpm.io/motivation".to_string()),
            tags: vec!["pnpm".to_string(), "lockfile".to_string(), "reproducible".to_string()],
            env_var: false,
            binary: false,
        },
        // Go patterns
        Pattern {
            name: "go-mod".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"go\.mod"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Go module file detected".to_string(),
            reference: Some("https://go.dev/ref/mod".to_string()),
            tags: vec!["go".to_string(), "module".to_string(), "dependencies".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "go-sum".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"go\.sum"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Go checksum file detected".to_string(),
            reference: Some("https://go.dev/ref/mod#go-sum".to_string()),
            tags: vec!["go".to_string(), "checksum".to_string(), "integrity".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "go-replace-directive".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"(?i)replace\s+"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Go replace directive detected".to_string(),
            reference: Some("https://go.dev/ref/mod#go.sum".to_string()),
            tags: vec!["go".to_string(), "replace".to_string(), "dependency".to_string()],
            env_var: false,
            binary: false,
        },
        // Python patterns
        Pattern {
            name: "requirements-txt".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"requirements.*\.txt"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Python requirements file detected".to_string(),
            reference: Some("https://pip.pypa.io/en/stable/user_guide/#requirements-files".to_string()),
            tags: vec!["python".to_string(), "pip".to_string(), "dependencies".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "pipfile".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"Pipfile"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Pipfile detected".to_string(),
            reference: Some("https://pipenv.pypa.io/en/latest/basics/".to_string()),
            tags: vec!["python".to_string(), "pipenv".to_string(), "dependencies".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "pipfile-lock".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"Pipfile\.lock"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Pipfile.lock detected".to_string(),
            reference: Some("https://pipenv.pypa.io/en/latest/basics/#pipfile-lock".to_string()),
            tags: vec!["python".to_string(), "pipenv".to_string(), "lockfile".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "pyproject-toml".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"pyproject\.toml"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Python pyproject.toml detected".to_string(),
            reference: Some("https://packaging.python.org/en/latest/specifications/pyproject-toml/".to_string()),
            tags: vec!["python".to_string(), "packaging".to_string(), "build".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "poetry-lock".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"poetry\.lock"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Poetry lock file detected".to_string(),
            reference: Some("https://python-poetry.org/docs/basic-usage/#locking-your-dependencies".to_string()),
            tags: vec!["python".to_string(), "poetry".to_string(), "lockfile".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "setup-py".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"setup\.py"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Python setup.py detected".to_string(),
            reference: Some("https://setuptools.pypa.io/en/latest/userguide/quickstart.html".to_string()),
            tags: vec!["python".to_string(), "setuptools".to_string(), "packaging".to_string()],
            env_var: false,
            binary: false,
        },
        // Rust patterns
        Pattern {
            name: "cargo-toml".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"Cargo\.toml"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Rust Cargo.toml detected".to_string(),
            reference: Some("https://doc.rust-lang.org/cargo/reference/manifest.html".to_string()),
            tags: vec!["rust".to_string(), "cargo".to_string(), "dependencies".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "cargo-lock".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"Cargo\.lock"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Rust Cargo.lock detected".to_string(),
            reference: Some("https://doc.rust-lang.org/cargo/reference/locking.html".to_string()),
            tags: vec!["rust".to_string(), "cargo".to_string(), "lockfile".to_string()],
            env_var: false,
            binary: false,
        },
        // Java/Gradle patterns
        Pattern {
            name: "pom-xml".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"pom\.xml"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Maven pom.xml detected".to_string(),
            reference: Some("https://maven.apache.org/guides/introduction/introduction-to-the-pom.html".to_string()),
            tags: vec!["java".to_string(), "maven".to_string(), "build".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gradle-build".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"build\.gradle"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Gradle build file detected".to_string(),
            reference: Some("https://docs.gradle.org/current/userguide/build_file_basics.html".to_string()),
            tags: vec!["java".to_string(), "gradle".to_string(), "build".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gradle-lockfile".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"gradle\.lockfile"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Gradle lockfile detected".to_string(),
            reference: Some("https://docs.gradle.org/current/userguide/dependency_locking.html".to_string()),
            tags: vec!["java".to_string(), "gradle".to_string(), "lockfile".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "maven-wrapper".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"mvnw"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Maven wrapper detected".to_string(),
            reference: Some("https://maven.apache.org/wrapper/".to_string()),
            tags: vec!["java".to_string(), "maven".to_string(), "wrapper".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "gradle-wrapper".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"gradlew"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Gradle wrapper detected".to_string(),
            reference: Some("https://docs.gradle.org/current/userguide/gradle_wrapper.html".to_string()),
            tags: vec!["java".to_string(), "gradle".to_string(), "wrapper".to_string()],
            env_var: false,
            binary: false,
        },
        // .NET patterns
        Pattern {
            name: "nuget-config".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"nuget\.config"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "NuGet config detected".to_string(),
            reference: Some("https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior".to_string()),
            tags: vec![".net".to_string(), "nuget".to_string(), "package-manager".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "packages-config".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"packages\.config"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: ".NET packages.config detected".to_string(),
            reference: Some("https://docs.microsoft.com/en-us/nuget/reference/packages-config".to_string()),
            tags: vec![".net".to_string(), "packages".to_string(), "dependencies".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dotnet-csproj".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"\.[a-z]+\.csproj"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: ".NET project file detected".to_string(),
            reference: Some("https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties".to_string()),
            tags: vec![".net".to_string(), "project".to_string(), "msbuild".to_string()],
            env_var: false,
            binary: false,
        },
        // Security/advisories
        Pattern {
            name: "github-advisory".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"github\.com/advisories"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GitHub security advisory reference detected".to_string(),
            reference: Some("https://github.com/advisories".to_string()), // aegis:ignore:github-advisory
            tags: vec!["github".to_string(), "advisory".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "npm-audit".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"(?i)npm\s+audit"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "NPM audit command detected".to_string(),
            reference: Some("https://docs.npmjs.com/cli/v8/commands/npm-audit".to_string()),
            tags: vec!["npm".to_string(), "audit".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "safety-db".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"(?i)safety\s+check"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Python safety check detected".to_string(),
            reference: Some("https://pypi.org/project/safety/".to_string()),
            tags: vec!["python".to_string(), "safety".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "cargo-audit".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"(?i)cargo\s+audit"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Cargo audit command detected".to_string(),
            reference: Some("https://crates.io/crates/cargo-audit".to_string()),
            tags: vec!["rust".to_string(), "audit".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        // SBOM patterns
        Pattern {
            name: "sbom-spdx".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"SPDXID.*DocumentName"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "SPDX SBOM detected".to_string(),
            reference: Some("https://spdx.dev/".to_string()),
            tags: vec!["sbom".to_string(), "spdx".to_string(), "software-bill-of-materials".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "sbom-cyclonedx".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"<bom.*xmlns.*cyclonedx"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CycloneDX SBOM detected".to_string(),
            reference: Some("https://cyclonedx.org/".to_string()),
            tags: vec!["sbom".to_string(), "cyclonedx".to_string(), "software-bill-of-materials".to_string()],
            env_var: false,
            binary: false,
        },
        // Container images
        Pattern {
            name: "dockerfile-base-image".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"(?i)^FROM\s+[a-z0-9._/-]+:([a-z0-9._-]+|latest)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Docker base image reference detected".to_string(),
            reference: Some("https://docs.docker.com/engine/reference/builder/#from".to_string()),
            tags: vec!["docker".to_string(), "container".to_string(), "base-image".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "helm-chart-dependency".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"dependencies:.*- name:"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Helm chart dependency detected".to_string(),
            reference: Some("https://helm.sh/docs/topics/charts/#chart-dependencies".to_string()),
            tags: vec!["helm".to_string(), "kubernetes".to_string(), "dependency".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "github-actions-workflow".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"\.github/workflows/"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GitHub Actions workflow detected".to_string(),
            reference: Some("https://docs.github.com/en/actions/learn-github-actions".to_string()),
            tags: vec!["github".to_string(), "ci".to_string(), "actions".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dependabot-config".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"dependabot\.yml"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Dependabot configuration detected".to_string(),
            reference: Some("https://docs.github.com/en/code-security/dependabot".to_string()),
            tags: vec!["github".to_string(), "dependabot".to_string(), "updates".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "renovate-config".to_string(),
            category: "supply-chain".to_string(),
            match_pattern: r#"renovate\.json"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Renovate configuration detected".to_string(),
            reference: Some("https://docs.renovatebot.com/".to_string()),
            tags: vec!["renovate".to_string(), "updates".to_string(), "dependencies".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
