//! Terraform patterns

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "db-public-access".to_string(),
            category: "terraform".to_string(),
            match_pattern: r#"(?i)publicly_accessible\s*=\s*true|skip_final_snapshot\s*=\s*true"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Database instance configured with public accessibility".to_string(),
            reference: None,
            tags: vec!["terraform".to_string(), "database".to_string(), "aws".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "tf-ecs-no-secrets".to_string(),
            category: "terraform".to_string(),
            match_pattern: r#"aws_ecs_task_definition"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "ECS task definition detected - ensure secrets are not hardcoded".to_string(),
            reference: None,
            tags: vec!["terraform".to_string(), "ecs".to_string(), "aws".to_string(), "secrets".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "tf-ecs-privileged".to_string(),
            category: "terraform".to_string(),
            match_pattern: r#"aws_ecs_task_definition[^{]*\{[^}]*privileged\s*=\s*true"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "ECS task definition with privileged mode enabled".to_string(),
            reference: None,
            tags: vec!["terraform".to_string(), "ecs".to_string(), "aws".to_string(), "privilege".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hardcoded-tf-secrets".to_string(),
            category: "terraform".to_string(),
            match_pattern: r#"(?i)(password\s*=\s*["'][^"']{8,}["']|secret\s*=\s*["'][^"']{8,}["']|api_key\s*=\s*["'][^"']{8,}["']|aws_access_key\s*=\s*["'][^"']{8,}["']|aws_secret_key\s*=\s*["'][^"']{8,}["'])"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Hardcoded secrets detected in Terraform configuration".to_string(),
            reference: None,
            tags: vec!["terraform".to_string(), "secrets".to_string(), "aws".to_string(), "hardcoded".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "s3-public-access".to_string(),
            category: "terraform".to_string(),
            match_pattern: r#"(?i)acl\s*=\s*["']public-read["']|acl\s*=\s*["']public-read-write["']|acl\s*=\s*["']aws-auth["']|block_public_acls\s*=\s*false|block_public_policy\s*=\s*false"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "S3 bucket configured with public access".to_string(),
            reference: None,
            tags: vec!["terraform".to_string(), "s3".to_string(), "aws".to_string(), "public-access".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "tf-s3-unencrypted".to_string(),
            category: "terraform".to_string(),
            match_pattern: r#"aws_s3_bucket[^{]*\{[^}]*server_side_encryption_configuration\s*=\s*null"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "S3 bucket without server-side encryption".to_string(),
            reference: None,
            tags: vec!["terraform".to_string(), "s3".to_string(), "aws".to_string(), "encryption".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "unencrypted-storage".to_string(),
            category: "terraform".to_string(),
            match_pattern: r#"(?i)encrypted\s*=\s*false|encryption\s*=\s*false|server_side_encryption_configuration\s*=\s*null"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Storage resource configured without encryption".to_string(),
            reference: None,
            tags: vec!["terraform".to_string(), "storage".to_string(), "aws".to_string(), "encryption".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
