//! Web development patterns

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "bundler-optimization".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#"import.*\*.*from|require.*dynamic.*import|import.*\(?.*await"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Bundler optimization issue".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "bundler".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "error-boundaries".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#"componentDidCatch|getDerivedStateFromError|class.*ErrorBoundary"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "React error boundary implementation".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "react".to_string(), "error-handling".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "form-validation".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#"form.*onSubmit.*preventDefault|input.*required.*false|pattern.*validation"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Form validation issue".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "forms".to_string(), "validation".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "incorrect-semantic-html".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#"<div\s+class=".*container.*"><div\s+class=".*row.*"><div\s+class=".*col.*"|<div\s+role="navigation"|<div\s+role="main""#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Incorrect semantic HTML usage".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "accessibility".to_string(), "html".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "inefficient-css".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#"@import.*css|style.*attribute.*important|\*.*\{.*display.*none|animation.*no.*hardware"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Inefficient CSS implementation".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "css".to_string(), "performance".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-prop-validation".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#"PropsTypes|propTypes.*isRequired|React\.PropTypes.*\.isRequired"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Missing prop type validation".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "react".to_string(), "prop-types".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "nextjs".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#"useEffect.*\[\].*fetch|export default.*function.*props|getStaticPaths.*fallback.*false"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Next.js specific pattern".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "nextjs".to_string(), "react".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "poor-error-boundary".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#"componentDidCatch.*console\.log|ErrorBoundary.*return.*null|catch.*error.*render.*null"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Poor error boundary implementation".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "react".to_string(), "error-handling".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "react-optimization".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#"useCallback.*\[\]|useMemo.*\[\]|React\.memo.*props.*object"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "React optimization issue".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "react".to_string(), "performance".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "seo-meta-tags".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#"<!DOCTYPE html>|<meta name="description"|<meta property="og:|<link rel="canonical"|<meta name="keywords""#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "SEO meta tag configuration".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "seo".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "state-management".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#"useState.*useEffect.*useState|setState.*prevState|dispatch.*action.*type"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "State management issue".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "state-management".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "typescript-any".to_string(),
            category: "web_development".to_string(),
            match_pattern: r#":\s*any\b|as\s+any\b"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "TypeScript any type usage".to_string(),
            reference: None,
            tags: vec!["web_development".to_string(), "typescript".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
