//! Web security patterns - OWASP Top 10 and web vulnerabilities

use crate::Pattern;

pub fn get() -> Vec<Pattern> {
    vec![
        Pattern {
            name: "reflected-xss".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(request\.params|request\.query|request\.body|req\.params)\.[\w_]+\s*\+"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential reflected XSS vulnerability".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/xss/".to_string()),
            tags: vec!["xss".to_string(), "security".to_string(), "web".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "sql-injection".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)query\s*\([^)]*\+[^)]*\)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential SQL injection vulnerability".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/SQL_Injection".to_string()),
            tags: vec!["sql".to_string(), "injection".to_string(), "security".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "cors-misconfiguration".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(Access-Control-Allow-Origin.*\*|allow.*origin.*\*)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CORS misconfiguration detected (wildcard origin)".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/csrf".to_string()),
            tags: vec!["cors".to_string(), "security".to_string(), "web".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "stored-xss".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)innerHTML\s*=|outerHTML\s*="#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential stored XSS via innerHTML".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/xss/".to_string()),
            tags: vec!["xss".to_string(), "security".to_string(), "stored".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "dom-xss".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(document\.write|eval\(|new\s+Function\()"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Potential DOM XSS vulnerability".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/xss/".to_string()),
            tags: vec!["xss".to_string(), "security".to_string(), "dom".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "xss-via-url".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(window\.location|document\.URL|document\.referrer)[^\;]*\+"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential XSS via URL parameters".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/xss/".to_string()),
            tags: vec!["xss".to_string(), "security".to_string(), "url".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "csrf-missing-token".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(POST|PUT|DELETE)\s*\([^)]*\)(?!.*csrf|.*token|.*xsrf)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "State-changing operation may lack CSRF protection".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/csrf".to_string()),
            tags: vec!["csrf".to_string(), "security".to_string(), "web".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "csrf-token-header".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)X-CSRF-Token|XSRF-TOKEN|csrf-token"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "CSRF token header detected".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/csrf".to_string()),
            tags: vec!["csrf".to_string(), "security".to_string(), "token".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "command-injection".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(exec|spawn|system|popen)\s*\([^)]*\+"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Potential OS command injection".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/Command_Injection".to_string()),
            tags: vec!["command-injection".to_string(), "security".to_string(), "os".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "path-traversal".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(readFile|readFileSync|open|fs\.).*\+.*(?:user|input|param|query)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential path traversal vulnerability".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/Path_Traversal".to_string()),
            tags: vec!["path-traversal".to_string(), "security".to_string(), "file".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "directory-traversal".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"\.\./|\.\.\\|%2e%2e%2f|%2e%2e/"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Directory traversal pattern detected".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/Path_Traversal".to_string()),
            tags: vec!["path-traversal".to_string(), "security".to_string(), "injection".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "ssrf".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(fetch|axios|request|httpClient)\s*\(.*(?:url|uri|href|src).*\)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential Server-Side Request Forgery (SSRF)".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/Server_Side_Request_Forgery".to_string()),
            tags: vec!["ssrf".to_string(), "security".to_string(), "web".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "ssrf-localhost".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(localhost|127\.0\.0\.1|0\.0\.0\.0|metadata\.google)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential SSRF targeting internal resources".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/Server_Side_Request_Forgery".to_string()),
            tags: vec!["ssrf".to_string(), "security".to_string(), "internal".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-security-headers".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)X-Content-Type-Options|X-XSS-Protection|Content-Security-Policy"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Security headers detected".to_string(),
            reference: Some("https://owasp.org/www-community/projects/verification".to_string()),
            tags: vec!["security-headers".to_string(), "security".to_string(), "web".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hsts-missing".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)Strict-Transport-Security"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "HSTS header not detected".to_string(),
            reference: Some("https://hstspreload.org/".to_string()),
            tags: vec!["hsts".to_string(), "security".to_string(), "https".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "x-frame-options".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)X-Frame-Options"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "X-Frame-Options header detected".to_string(),
            reference: Some("https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options".to_string()),
            tags: vec!["x-frame-options".to_string(), "security".to_string(), "clickjacking".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "x-content-type-options".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)X-Content-Type-Options.*nosniff"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "X-Content-Type-Options header detected".to_string(),
            reference: Some("https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options".to_string()),
            tags: vec!["x-content-type-options".to_string(), "security".to_string(), "mime".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "content-security-policy".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)Content-Security-Policy"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Content-Security-Policy header detected".to_string(),
            reference: Some("https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP".to_string()),
            tags: vec!["csp".to_string(), "security".to_string(), "xss".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "hardcoded-credential".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(username|password|credential)\s*=\s*['\"][^'\"]{4,}"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Hardcoded credential detected".to_string(),
            reference: Some("https://owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure".to_string()),
            tags: vec!["credential".to_string(), "security".to_string(), "hardcoded".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "weak-password-hash".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(md5|sha1|des|crypt)\s*\(.*password"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Weak password hashing algorithm detected".to_string(),
            reference: Some("https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html".to_string()),
            tags: vec!["password".to_string(), "security".to_string(), "hashing".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "jwt-none-algorithm".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(alg.*none|algorithm.*none|none.*algorithm)"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "JWT with 'none' algorithm detected".to_string(),
            reference: Some("https://owasp.org/www-project-web-security-testing/latest/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens".to_string()),
            tags: vec!["jwt".to_string(), "security".to_string(), "algorithm".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "session-fixation".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)session\s*=\s*request\.getParameter|sessionId.*getParameter"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Potential session fixation vulnerability".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/Session_fixation".to_string()),
            tags: vec!["session".to_string(), "security".to_string(), "authentication".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "xxe".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(DocumentBuilder|SAXParser|XMLReader|XMLInputFactory).*disabled"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "XXE protection disabled".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/XML_External_Entities_(XXE)_Processing".to_string()),
            tags: vec!["xxe".to_string(), "security".to_string(), "xml".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "xml-external-entity".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)<!ENTITY|SYSTEM\s+\"|PUBLIC\s+\""#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "XML External Entity (XXE) detected".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/XML_External_Entities_(XXE)_Processing".to_string()),
            tags: vec!["xxe".to_string(), "security".to_string(), "xml".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "insecure-deserialization".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(unpickle|unserialize|ObjectInputStream|YAML\.load)\s*\("#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Potential insecure deserialization".to_string(),
            reference: Some("https://owasp.org/www-community/attacks/Insecure_Deserialization".to_string()),
            tags: vec!["deserialization".to_string(), "security".to_string(), "rce".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "unrestricted-file-upload".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(multipart|fileUpload|uploadFile).*without.*validation"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "File upload without validation".to_string(),
            reference: Some("https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload".to_string()),
            tags: vec!["file-upload".to_string(), "security".to_string(), "web".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "executable-file-upload".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)\.(exe|sh|php|asp|jsp)\s*.*upload|move_uploaded_file"#.to_string(),
            enabled: true,
            severity: "critical".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Executable file upload detected".to_string(),
            reference: Some("https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload".to_string()),
            tags: vec!["file-upload".to_string(), "security".to_string(), "rce".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "open-redirect".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(redirect|forward|location)\s*\([^)]*request\.(params|query|body)"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "Potential open redirect vulnerability".to_string(),
            reference: Some("https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html".to_string()),
            tags: vec!["redirect".to_string(), "security".to_string(), "phishing".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "redirect-to-relative".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)redirect\s*\(\s*\/[^\)]"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Redirect to relative path".to_string(),
            reference: None,
            tags: vec!["redirect".to_string(), "security".to_string(), "relative".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "debug-mode".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(debug\s*=\s*true|DEBUG\s*=\s*true|app\.env\s*=\s*['\"]dev['\"])"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Debug mode enabled in production".to_string(),
            reference: None,
            tags: vec!["debug".to_string(), "security".to_string(), "disclosure".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "stack-trace-exposure".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)stack\s*trace|exception.*print|printStackTrace"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Stack trace exposure detected".to_string(),
            reference: None,
            tags: vec!["stack-trace".to_string(), "security".to_string(), "disclosure".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "server-version".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)Server|X-Powered-By|X-AspNet-Version"#.to_string(),
            enabled: true,
            severity: "low".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Server version header detected".to_string(),
            reference: None,
            tags: vec!["server".to_string(), "security".to_string(), "disclosure".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "rate-limiting".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)rate\s*limit|throttle|rateLimit"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "Rate limiting detected".to_string(),
            reference: None,
            tags: vec!["rate-limiting".to_string(), "security".to_string(), "api".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "api-key-exposure".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(api[_-]?key|apikey)\s*[:=]\s*['\"][A-Za-z0-9]{16,}"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "API key in source code".to_string(),
            reference: None,
            tags: vec!["api-key".to_string(), "security".to_string(), "credential".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "missing-authentication".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)(@GetMapping|@PostMapping|@RequestMapping)(?!.*secured|.*auth|.*permitAll)"#.to_string(),
            enabled: true,
            severity: "high".to_string(),
            confidence: "medium".to_string(),
            min_entropy: None,
            description: "API endpoint may lack authentication".to_string(),
            reference: None,
            tags: vec!["authentication".to_string(), "security".to_string(), "api".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "graphql-introspection".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)introspection.*true|__schema"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GraphQL introspection enabled".to_string(),
            reference: None,
            tags: vec!["graphql".to_string(), "security".to_string(), "introspection".to_string()],
            env_var: false,
            binary: false,
        },
        Pattern {
            name: "graphql-batch-limit".to_string(),
            category: "web-security".to_string(),
            match_pattern: r#"(?i)query\s*depth|maxDepth|batch.*limit"#.to_string(),
            enabled: true,
            severity: "medium".to_string(),
            confidence: "high".to_string(),
            min_entropy: None,
            description: "GraphQL depth limiting detected".to_string(),
            reference: None,
            tags: vec!["graphql".to_string(), "security".to_string(), "depth-limit".to_string()],
            env_var: false,
            binary: false,
        },
    ]
}
